<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/js-xlsx-master/dist/xlsx.full.min.js'))
        ->appendFile($this->basePath('js/recruitment/rollno/index.js'));
?>

<?php if ($this->messages) { ?>
    <script>
        // document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    // document.updateFlatValuesLink = '<?php echo $this->url("excelUpload", ["action" => "updateFlatValues"]); ?>';
    document.uploadUrl = '<?php echo $this->url('rollno', ["action" => "excelUpload"]); ?>';
    // document.updateMonthlyValuesLink = '<?php echo $this->url("excelUpload", ["action" => "updateMonthlyValues"]); ?>';
    // document.updatePayValuesLink = '<?php echo $this->url("excelUpload", ["action" => "updatePayValues"]); ?>';
    // document.flatValues =<?php echo json_encode($flatValues); ?>;
    // document.payValues =<?php echo json_encode($payValues); ?>;
    // document.salaryTypes =<?php echo json_encode($salaryTypes); ?>;
    // document.monthlyValues =<?php echo json_encode($monthlyValues); ?>;
    // document.fiscalYears =<?php echo json_encode($fiscalYears); ?>;
    // document.months =<?php echo json_encode($months); ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    // document.maxFiscalYearId =<?php echo $maxFiscalYearId; ?>;
</script>

<div class="page-bar">
   <?= $this->navigation('Zend\Navigation\rollno')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div>
    <div class="row">
        <div class="col-sm-12 ">
            <div class="portlet light bg-inverse">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-paper-plane font-green-haze"></i>
                        <span class="caption-subject bold font-green-haze uppercase"> Import From Excel For Roll No</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <label>Browse File:
                                <input type="file" name="excelImport" id="excelImport">
                            </label>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <label>Generate admit card?</label>
                            <input type="checkbox" id="generateAdmit" name="generateAdmit">
                        </div>

                        <div class="col-sm-2">
                            <label>Send mail? </label>
                            <input type="checkbox" id="sendMail" name="sendMail">
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-2">
                            <input type="button" name="submit" id="submit" value="Submit" class="btn btn-primary">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div id="table"></div> -->



