<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/recruitment/vacancystage/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'vacancystageForm');

$VacancyId = $form->get('VacancyId');
$VacancyId->setValueOptions($VacancyList);
$RecStageId = $form->get('RecStageId');
$RecStageId->setValueOptions($RecStageList);
$Remark = $form->get('Remark');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('vacancystage', ['action' => 'add']));
$form->prepare();
?>

<script>
    document.viewLink = '<?= $this->url("vacancystage", ["action" => "view"]) ?>';
    document.editLink = '<?= $this->url("vacancystage", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("vacancystage", ["action" => "delete"]) ?>';
    
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancystage')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>
                    <div class="row">                    
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($VacancyId); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($VacancyId); ?>
                                <?php print $this->formElementErrors()->render($VacancyId, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($RecStageId); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($RecStageId); ?>
                                <?php print $this->formElementErrors()->render($RecStageId, ['class' => 'help-block']); ?>
                            </div>
                        </div>  
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($Remark); ?>
                                <?php print $this->formElement($Remark); ?>
                                <?php print $this->formElementErrors()->render($Remark, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>         
                    <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
    </div>
</div>