<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/recruitment/vacancystage/index.js'));

?>

<script>
    document.viewLink = '<?= $this->url("vacancystage", ["action" => "view"]) ?>';
    document.editLink = '<?= $this->url("vacancystage", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("vacancystage", ["action" => "delete"]) ?>';
    document.ids =<?php echo json_encode(["AdNo" => ""]) ?>;
    document.bulkStageWS = '<?php echo $this->url('vacancystage', ['action' => 'bulkStageWS']); ?>';
    document.adno = <?php echo json_encode($Adno); ?>;
    document.openings = <?php echo json_encode($opening); ?>;
    
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancystage')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">        
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group">                
                    <!-- <label for="AdNo">Ad Number</label>
                    <input type="text" id="AdNo" name="AdNo"  class="form-control reset-field"/> -->
                    <label>Opening Number</label>
                    <select class="form-control" name="opening" id="openingId">
                    </select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">                
                    <!-- <label for="AdNo">Ad Number</label>
                    <input type="text" id="AdNo" name="AdNo"  class="form-control reset-field"/> -->
                    <label>Ad Number</label>
                    <select multiple class="form-control" name="adnumber" id="adnumberId">
                    </select>
                </div>
            </div>
        </div>
    </div>
            <div class="row margin-top-10">
                <div class="col-sm-offset-8 col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
            </div>
        </div>
    </div>
    <div class="margin-top-20">
    <div id="VacancystageTable">
    </div>
</div>

<!-- Select Option  -->
    <div style="display: none;" class="row margin-top-20" id="acceptRejectDiv" >
            <?php  if(1==1){  ?>
            <div class="col-sm-2 ">
                <!-- <button id="A" class="btn btn-danger btnApproveReject">Reject</button> -->
            </div>
            <div class="col-sm-2 manualShift">
                <label>Stages</label>
                <select id="StageId" name="StageId">
                <option value="0" selected="selected">---</option>
                <?php foreach($Stages as $Stage){ ?>
                    <option value="<?=$Stage['REC_STAGE_ID']?>"><?=$Stage['STAGE_EDESC']?></option>
                <?php } ?>
                </select>
            </div>
            <!-- <div class="col-sm-2 col-sm-offset-8"> -->
            <div class="col-sm-2">
                <button id="update" class="btn btn-info btnApproveReject pull-right">Update Stage</button>
            </div>
            <?php }      ?>
        </div>
    </div>
</div>

