<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\advance-request')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/advance/advance-request/add.js'));
?>


<?php
//echo '<pre>';print_r($employees);die;
$form->setAttribute('role', 'form');

$leaveId = $form->get('leaveId');
$leaveId->setValueOptions($leave_types);
$requestedDays = $form->get('requestedDays');
$reason = $form->get('reason');

//Add employees
$empId = $form->get('empId');
$empId->setValueOptions($employees);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply Leave Encashment');
$submit->setAttribute('id', 'request');
//
$form->setAttribute('action', $this->url('LeaveEncashmenthr', ['action' => 'add']));
// $form->setAttribute('action', '/neo-hris/public/leavemanagement/LeaveEncashmenthr/add');

$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.employeeId =<?= json_encode($employeeId); ?>;
    document.salary =<?= $salary ?>;
    document.advanceList =<?= json_encode($advance); ?>;
    document.employeeList =<?= json_encode($employeeList); ?>;
</script>
<?php
/*if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}*/
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>


<div class="row margin-top-20" >
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>
                    Apply For Leave Encashment
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="form-group">
                    <input type="hidden" name="employeeId" id="employeeId" value="<?php echo $employeeId; ?>"/>
                    <input type="hidden" name="deductionType" id="deductionType" />
                </div>

                <?php
                /*
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <label for= "accumulated_days">Accumulated Days</label>
                            <input type="text" name="accumulated_days" id="accumulated_days" class=" form-control" min="1" value="<?php echo $total_accum_days; ?>" autocomplete="off" readonly="readonly">
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                        <label for= "available_days_encash">Maximum Days to Encash</label>
                            <input type="text" name="available_days_encash" id="available_days_encash" class=" form-control" min="1" value="<?php echo $no_of_leaves_to_apply; ?>" autocomplete="off" readonly="readonly">
                        </div>
                    </div>
                </div>
               


                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12" >
                        <hr>
                    </div>
                </div>
                 */
                ?>

                <!-- for all employees -->
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($empId->getMessages()) ? "" : "error" ?> ">
                            <?php print $this->formLabel($empId) ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeId" id="employeeId" required="required"  class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                        </div>
                        <?php print $this->formElementErrors()->render($empId, ['class' => 'help-block error']); ?> 
                    </div>
                </div>

                <!-- all employees select ends -->

                <div class="row">

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($leaveId); ?>
                            <?php print $this->formElement($leaveId); ?>
                            <?php print $this->formElementErrors()->render($leaveId, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($requestedDays); ?>
                            <?php print $this->formElement($requestedDays); ?>
                            <?php print $this->formElementErrors()->render($requestedDays, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-sm-12 col-md-6 col-lg-4" >
                        <div class="form-group">
                            <?php print $this->formLabel($reason); ?>
                            <?php print $this->formElement($reason); ?>
                            <?php print $this->formElementErrors()->render($reason, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                </div>
                <div>
                    <div><span id="defaultValues" class="clearText"></span></div>
                    <div><span id="monthlyDeductionAmt" class="clearText"></span></div>
                    <div><span id="maxReqAmt" class="clearText"></span></div>
                    <div><span id="overrideDeductionPer" class="clearText"></span></div>
                    <div><span id="overrideDeductionMonth" class="clearText"></span></div>

                </div>

                <span id="beforeSubmitVal" class="errorMsg"></span></br>

                <?php print $this->formSubmit($submit); ?>

            </div>
        </div>
    </div>
</div>
<?php
print $this->form()->closeTag();
?>
