<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.rtl.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.dataviz.default.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/LeaveManagement/leave-encashmenthr/index.js'));
?>
<script>
    document.currentMonth=<?=$currentMonth?>;
    document.monthList=<?= json_encode($leaveMonthData)?>;
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.getFiscalYearMonthLink = '<?php echo $this->url('leave', ['action' => 'getFiscalYearMonth']); ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\leave')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
            <?php //if ($acl['ALLOW_ADD'] == 'Y'): ?>
                    <a href="<?= $this->url('LeaveEncashmenthr', ['action' => 'add']) ?>" class="btn default btn-sm">
                        <i class="fa fa fa-arrow-right icon-black"></i>
                        Apply for Leave Encashment 
                    </a>
<?php //endif; ?>

                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> 
                                Export to Excel 
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    
        <div class="portlet-body">
            <div class="row">
                 <div class="col-sm-4">
                        <div class="form-group">
                            <label>Employee</label>
                            <span class="required" aria-required="true">*</span>
                            <select multiple name="employeeId" id="employeeId" required="required"  class="form-control">
                                                           
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                        </div>
            

                        
                    </div>
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
                
               
           
        
                    <div class="col-sm-4 ">
                        <label>Fiscal Year</label>
                        <select name="leaveId" id="leaveId" required="required"  class="form-control">
                                                                
                                                                <?php foreach ($leave_year as $key => $value) { ?>
                                                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                                                <?php } ?>
                                                            </select>
                </div> 

             </div>
            
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <label height="45"></label>
                    <button  id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>


        <div id="leaveEncashmentTable">
        </div>
    </div>    
    <div>
<!--        <div class="row margin-top-20">-->
<!--            <div class="col-sm-2">-->
<!--                <select id="leaveMonth"></select>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div id="monthlyLeaveTable">-->

        </div>
    </div>
</div>