<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelApprove')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('dropzone/dropzone.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()
        ->appendFile($this->basePath('js/manager-service/travel-approve/view.js'));

$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$fromDate->setAttributes(["disabled" => "disabled"]);
$toDate = $form->get('toDate');
$toDate->setAttributes(["disabled" => "disabled"]);
$requestedAmount = $form->get('requestedAmount');
$requestedAmount->setAttributes(["disabled" => "disabled"]);
$departure = $form->get('departure');
$departure->setAttributes(["disabled" => "disabled"]);
$destination = $form->get('destination');
$destination->setAttributes(["disabled" => "disabled"]);
$purpose = $form->get('purpose');
$purpose->setAttributes(["disabled" => "disabled"]);
$remarks = $form->get('remarks');
$remarks->setAttributes(["disabled" => "disabled"]);
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions([$detail['REQUESTED_TYPE'] => $detail['REQUESTED_TYPE_DETAIL']]);
$requestedType->setAttributes(["disabled" => "disabled"]);
$transportType = $form->get('transportTypeList');
$transportType->setAttribute('multiple','multiple');
$transportType->setValueOptions($transportTypes);
$transportType->setAttributes(['disabled' => "disabled"]);
$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(['required' => 'true']);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(['required' => 'true']);

$noOfDays = $form->get('noOfDays');
$noOfDays->setAttributes(['disabled' => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'Approve');
$submit->setAttribute('id', 'approve');

$form->setAttribute('action', $this->url('travelStatus', ['action' => 'action', 'id' => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.uploadUrl = '<?= $this->url("travelRequest", ["action" => "fileUpload"]); ?>';
    document.pushDCFileLink = '<?php echo $this->url('travelRequest', ['action' => 'pushDCFileLink']); ?>';
    document.pullFilebyId = '<?php echo $this->url('travelRequest', ['action' => 'pullFilebyId']); ?>';
    document.id = '<?php echo $id; ?>';
    document.status = '<?php echo $status; ?>';
</script>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Travel Request Detail
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="border-bottom">
                <div class="form-group">
                    <div class="row div-font-11">
                        <div class="col-sm-4">
                            <table>
                                <tr height="30">
                                    <td>
                                        Employee Name
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['FULL_NAME']; ?>
                                    </td>
                                </tr>
                                <tr height="30">
                                    <td>
                                        Recommender
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $recommender ?>
                                    </td>
                                </tr>  

                                <tr height="30">
                                    <td>
                                        Advance Amount
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        Rs.<?php echo $detail['REQUESTED_AMOUNT']; ?>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-sm-4">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Requested Date
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['REQUESTED_DATE']; ?>
                                    </td>
                                </tr>

                                <tr height="30">
                                    <td>
                                        Approver
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?= $approver ?>
                                    </td>
                                </tr>     
                            </table>
                        </div>

                        <div class="col-sm-4">
                            <table>  
                                <tr height="30">
                                    <td>
                                        Status
                                    </td>
                                    <td width="15">:</td>
                                    <td>
                                        <?php echo $detail['STATUS_DETAIL']; ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($fromDate); ?>
                                    <?php print $this->formElement($fromDate); ?>
                                    <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliStartDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>        

                    </div>

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($toDate); ?>
                                    <?php print $this->formElement($toDate); ?>
                                    <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>     
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliEndDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                               class="form-control" value="" disabled="disabled">
                                    </div>
                                </div>
                            </div>     
                        </div>        

                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($purpose); ?>
                            <?php print $this->formElement($purpose); ?>
                            <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                </div>


                <div class=" row">
                    <?php if(!$itnaryId){ ?>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($departure); ?>
                            <?php print $this->formElement($departure); ?>
                            <?php print $this->formElementErrors()->render($departure, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($destination); ?>
                            <?php print $this->formElement($destination); ?>
                            <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <?php } ?>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($requestedAmount); ?>
                            <?php print $this->formElement($requestedAmount); ?>
                            <?php print $this->formElementErrors()->render($requestedAmount, ['class' => 'help-block']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($requestedType); ?>
                            <?php print $this->formElement($requestedType); ?>
                            <?php print $this->formElementErrors()->render($requestedType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                    
                    <div class="col-sm-4">
                        <div
                            class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($noOfDays); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($transportType); ?>
                            <?php print $this->formElement($transportType); ?>
                            <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
 
                <?php if(!empty($files)){ ?>
                        <div class="row"> 
                            <div class="col-sm-6"> 
                                <label>Attachments</label>
                                    <div style="overflow: scroll; height:100px;" >
                                        <ul> 
                                            <?php foreach($files as $file){ ?>
                                                <a target="_blank" href="<?='../../../uploads/travel_documents/'.$file['FILE_IN_DIR_NAME']?>">
                                                    <li><?=$file['FILE_NAME']?></li></a>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                        </div>
                    <?php } ?>

                <?php if (isset($detail['SUB_EMPLOYEE_ID'])) { ?>
                    <div class="form-group padding-0">
                        <label for="noOfDays">
                            Substitute Employee 

                        </label>
                        <div>
                            <select disabled="disabled" class="form-control" name="travelSubstitute">
                                <option style="cursor: pointer;" value="<?php echo $detail['SUB_EMPLOYEE_ID']; ?>" selected="selected"><?php echo $detail['SUB_EMPLOYEE_NAME']; ?></option>
                            </select>
                        </div>
                    </div>
                    <div
                        class="form-group margin-top-10 required">
                        <label>Reason for action [From Substitute Employee] <?php echo $detail['SUB_APPROVED_FLAG_DETAIL']; ?></label>
                        <textarea disabled name="subRemarks" id="form-subRemarks" required="required" class="form-subRemarks form-control" style="height: 50px; font-size:12px"><?php echo $detail['SUB_REMARKS']; ?></textarea>
                    </div>
                <?php } ?>
            </div>     
            <?php $recommendedRemarks->setAttributes(['disabled' => 'disabled']); ?>
            <div
                class="form-group margin-top-10 required <?= empty($recommendedRemarks->getMessages()) ? "" : "error" ?>">
                    <?php print $this->formLabel($recommendedRemarks); ?>
                    <?php print $this->formElement($recommendedRemarks); ?>
            </div>
            <div
                class="form-group required <?= empty($approvedRemarks->getMessages()) ? "" : "error" ?>">
                <label>Reason for action [From Approver]</label>
                <?php print $this->formElement($approvedRemarks); ?>
            </div>

            <div class= "row">
                    <div class=" col-md-6 form-group">
                        <table id="fileDetailsTbl" class="table">
                            <tr>
                                <th>Document</th>
                                <th>&nbsp;</th>
                                <!-- <th>Action</th> -->
                            </tr>
                        </table>
                    </div>
                    <?php if ($detail['STATUS'] == 'RQ' || ($detail['STATUS'] == 'RC')) { ?>
               
               <?php  if($acl['HR_APPROVE']=='Y'){  ?>
                    <div class="col-md-3">
                        <button id="addDocument" type="button" class="btn btn-primary">
                            Add
                        </button>
                    </div>
                </div>
                <?php } else{     ?>
                </div>
            <?php } } else{ ?>
                </div>
                <?php } ?>
            <?php if ($detail['STATUS'] == 'RQ' || ($detail['STATUS'] == 'RC')) { ?>
               
                <?php  if($acl['HR_APPROVE']=='Y'){  ?>
                    
                    <?php print $this->formSubmit($submit); ?>
                    <input type="submit" name="submit" class="btn btn-danger pull-right" value="Reject">
                <?php }      ?>
            <?php } ?>
                    
                    
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                             if ($itnaryId) {
                            echo $this->partial('travel/travel-itnary-request/itnaryPartialView.phtml', [
                                'itnaryId' => $itnaryId,
                                'travelItnaryDet' => $travelItnaryDet,
                                'travelItnaryMemDet' => $travelItnaryMemDet
                            ]);
                             }
                            ?>

                        </div>
                    </div>
                    

        </div>

    </div>
</div>

<?php
print $this->form()->closeTag();
?>
<div style="border:1px solid; display: none;" id="printableArea" class="col-md-8">
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <ul id="headingList">
                <li>
                    <h2 style="color:#c00000;"><?= strtoupper($detail['COMPANY_NAME']); ?></h2></li>
                <li><h3>Travel Order Form</h3></li>
                <li style="margin-top:-25px;"><h5>As per the bylaw 101 sub bylaw 3 of Paragraph 10 of EAB, 2063</h5></li>
            </ul>
        </div>
    </div>

    <div class="row font-common" style="min-height: 70px; width:100%">
        <div class="dtlTravel" style="width:63%;">
            <ul id="personalInfo" style="color:#17365d;">
            <li style="margin-top:20px;">Issue Number: <?php echo $issueNum; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;1.&nbsp;&nbsp;&nbsp;&nbsp;Name of employee: <?php echo $detail['FULL_NAME']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;2.&nbsp;&nbsp;&nbsp;&nbsp;Designation: <?php echo $detail['DESIGNATION_TITLE']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;3.&nbsp;&nbsp;&nbsp;&nbsp;Office: <?php echo $detail['BRANCH_NAME']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;4.&nbsp;&nbsp;&nbsp;&nbsp;Propose of Travel: <?php echo $detail['PURPOSE']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;5.&nbsp;&nbsp;&nbsp;&nbsp;Destination: <?php echo $detail['DESTINATION']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;6.&nbsp;&nbsp;&nbsp;&nbsp;Mode of Transportation: <?php echo $detail['TRANSPORT_TYPE_LIST_DETAIL_STR']; ?></li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;7.&nbsp;&nbsp;&nbsp;&nbsp;Duration of Travel: 
                    <ul style="color:black;" id="personalInfo">
                        <li style="margin-top:10px;">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;From: &nbsp;&nbsp;&nbsp;&nbsp;AD: <?= $detail['FROM_DATE']; ?> &nbsp;&nbsp;&nbsp;&nbsp; BS: <?= $detail['FROM_DATE_BS']; ?>
                        </li>
                        <li>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AD: <?= $detail['TO_DATE']; ?> &nbsp;&nbsp;&nbsp;&nbsp; BS: <?= $detail['TO_DATE_BS']; ?>
                        </li>
                        <li>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total: <?= $detail['DURATION']; ?> Day<?= ($detail['DURATION'] > 1) ? "s" : "" ?>
                        </li>
                    </ul>
                </li>
                <li style="margin-top:20px; width:140%;">&nbsp;&nbsp;&nbsp;&nbsp;8.&nbsp;&nbsp;&nbsp;&nbsp;Advance Required For Travel: Rs. <?= $detail['REQUESTED_AMOUNT'] ?> (<?= $advanceAmount; ?>)</li>
                <li style="margin-top:20px;">&nbsp;&nbsp;&nbsp;&nbsp;9.&nbsp;&nbsp;&nbsp;&nbsp;Any special order during Travel: 
                <div style="margin-left:50px; margin-top:10px;">
                    <textarea rows="5" cols="85" style="padding:5px;"><?= $detail['APPROVED_REMARKS'] ?></textarea>
                </div>
                </li>
                <li style="margin-top:40px;color:black;font-weight:bold;">Travelling Persons Signature: </li>
                <li style="margin-top:40px;color:black;font-weight:bold;">Recommended By: <?= $detail['NAME_RECOMMENDER']; ?></li>
                <li style="margin-top:40px;color:black;font-weight:bold;">Approved By: <?= $detail['NAME_APPROVER']; ?></li>
                <div class="row" style="width:150%; color:black; margin-top:50px;">
            <h4 style="margin-bottom:3px;">Note:</h4>
 
                <p>
                Three Copies of this travel bill is to be made, one used during advance, one for HR department and third for the purpose of travel bill.
                </p>
        </div>
            </ul>
            
        </div>
        
        <div class="dtlDate" style="width:37%;">
            <ul id="personalInfo">
                <li>Date: &nbsp;&nbsp;&nbsp;&nbsp; AD: <?php echo $detail['REQUESTED_DATE']; ?>&nbsp;&nbsp;&nbsp;&nbsp;BS: <?php echo $detail['REQUESTED_DATE_BS']; ?></li>
            </ul>
        </div>  
    </div>
</div>
<div class="col-md-12" style="text-align:center;display:<?php echo $detail['STATUS'] == 'AP' ? 'block' : 'block'; ?>">
    <a class="btn btn-success" id="print"> Print</a>
</div>

<div id="documentUploadModel" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Document Upload</h4>
            </div>
            <div class="modal-body">
                <div class="modal-body" id="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!--<div id="dropZoneContainer" >-->
                            <div id="dropZoneContainer"  class="dropzone">
                            </div>
                            <div id="uploadErr">Please upload .pdf or .txt or .jpg or .png files only.</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button id='uploadSubmitBtn' class="btn btn-primary" type="button" >OK</button>
            <button id='uploadCancelBtn' class="btn btn-warning" type="button" >Cancel</button>
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        </div>
    </div>
</div>
