<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/overtime/status/view.js'));

?>

<script>
    document.urlOvertime = '<?= $this->url("overtimeRequest", ["action" => "index"]) ?>';
    document.id = <?=$id?>;
    document.subDetails = <?php echo json_encode($subDetails) ?>;
    document.approveRejectLink = '<?= $this->url("overtimeStatus", ["action" => "approveReject", "id"=>$id, "role"=>$role]) ?>'
</script>
<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export to Excel
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-3">
                    <label class="control-label">Employee</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['FULL_NAME']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Date</label>
                    <input disabled type="text" class="form-control" value="<?php echo ($detail['REQUESTED_DT_AD'] . ' A.D.    |    ' . $detail['REQUESTED_DT_BS'].' B.S.')?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Your Role</label>
                    <input disabled type="text" class="form-control" value="<?php
                                            if ($role == 3) {
                                                echo 'Approver';
                                            } else if ($role == 2) {
                                                echo 'Recommender';
                                            } else if ($role == 4) {
                                                echo 'Recommender\Approver';
                                            }
                                            ?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Month</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['MONTH_DESC']?>">
                </div>
            </div>
            <?php /* <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Requested OT Hours</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_OT_HOURS']?>">
                </div>

                <div class="col-sm-3">
                    <label class="control-label">Requested OT Days</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_OT_DAYS']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Lunch Allowance</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_LUNCH_ALLOWANCE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Night Allowance</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_NIGHT_ALLOWANCE']?>">
                </div>
            </div> */ ?>

            <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Approved OT Hours</label>
                    <input disabled type="text" id = "appOtHours" class="form-control" value="<?php echo $detail['TOTAL_APP_OT_HOURS']?>">
                </div>

                <div class="col-sm-3">
                    <label class="control-label">Approved OT Days</label>
                    <input disabled type="text" id = "appOtDays" class="form-control" value="<?php echo $detail['TOTAL_APP_OT_DAYS']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved Festive OT Days</label>
                    <input disabled type="text" id = "festiveOtDays" class="form-control" value="<?php echo $detail['APP_FESTIVE_OT_DAYS']?>">
                </div>

                <div class="col-sm-3">
                    <label class="control-label">Approved Total OT Days</label>
                    <input disabled type="text" id = "grandTotalOtDays" class="form-control" value="<?php echo $detail['GRAND_TOTAL_APP_OT_DAYS']?>">
                </div>
                
            </div>
            <?php /* <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Requested Locking Allowance</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_LOCKING_ALLOWANCE']?>">
                </div>

                <div class="col-sm-3">
                    <label class="control-label">Requested Satta Bida</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_SUBSTITUTE_LEAVE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Dashain Tihar Bida</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_DASHAIN_TIHAR_LEAVE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Total Satta Bida</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_GRAND_TOTAL_LEAVE']?>">
                </div>
            </div> */ ?>

            <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Approved Locking Allowance</label>
                    <input disabled type="text" id="appLockingAllowance" class="form-control" value="<?php echo $detail['TOTAL_APP_LOCKING_ALLOWANCE']?>">
                </div>

                <div class="col-sm-3">
                    <label class="control-label">Approved Satta Bida</label>
                    <input disabled type="text" id="totalLeave" class="form-control" value="<?php echo $detail['TOTAL_APP_SUBSTITUTE_LEAVE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved Dashain Tihar Bida</label>
                    <input disabled type="text" id = 'dashainTiharBida' class="form-control" value="<?php echo $detail['TOTAL_APP_DASHAIN_TIHAR_LEAVE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved Total Satta Bida</label>
                    <input disabled type="text" id='totalSattaBida' class="form-control" value="<?php echo $detail['TOTAL_APP_GRAND_TOTAL_LEAVE']?>">
                </div>
            </div>
            <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Approved Lunch Allowance</label>
                    <input disabled type="text" id="lunchAllowance" class="form-control" value="<?php echo $detail['TOTAL_APP_LUNCH_ALLOWANCE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved Night Allowance</label>
                    <input disabled type="text" id="appNightAllowance" class="form-control" value="<?php echo $detail['TOTAL_APP_NIGHT_ALLOWANCE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Status</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['STATUS']?>">
                </div>
            </div>
            <div id="table" style="margin-top:20px;">
            </div>
            <div style="display: block;" class="row margin-top-20" id="printBtnDiv" >
                <div class="col-md-12" style="text-align:center;">
                <br>
                <a class="btn btn-success" id="print"> Print</a>
                </div>
            </div> 
            <?php
            if( $detail['STATUS'] != 'Approved' && $detail['STATUS'] != 'Rejected'){

            if ($role == 2) {
                ?>
                    <div
                        class="form-group margin-top-30 required">
                        <label>Reason for action [From Recommender]</label>
                        <textarea class="form-control" rows="4" style="height: auto !important;" id="recommenderRemarks" name="recommenderRemarks"></textarea>
                    </div>
            <?php } ?>
            <?php
            if ($role == 3) {
                ?>
                    <div
                        class="form-group margin-top-30 required">
                        <label>Reason for action [From Approver]</label>
                        <textarea class="form-control" rows="4" style="height: auto !important;" id="approverRemarks" name="approverRemarks"></textarea>
                    </div>
            <?php } ?>
            <?php
            if ($role == 4) {
                ?>
                    <div
                        class="form-group margin-top-30 required">
                        <label>Reason for action [From Recommender/Approver]</label>
                        <textarea class="form-control" rows="4" style="height: auto !important;" id="raRemarks" name="raRemarks"></textarea>
                    </div>
            <?php }} ?>
            
            <?php 
            if( $detail['STATUS'] != 'Approved' && $detail['STATUS'] != 'Rejected'){
                ?>
            <input type="submit" name="submit" id="btnReject" class="btn btn-danger btnApproveReject" value="Reject">
            <input type="submit" name="submit" id="btnApprove" class="btn btn-primary btnApproveReject pull-right" value="Approve">
            <?php 
            }
                ?>

        </div>

        
    </div>
</div>

<div style="border:1px solid; display: none;" id="printableArea" class="col-md-8">
       <table>
           <tr>
           <td style='width:50%;'>
                <div style="display:flex;">
                    <img src = <?php echo ($this->basePath() . '/img/noc-login1.png');?> class="img-fluid" style="display: block;  margin-right: 20px; width: 50px;" align="center">
                    <h1 style = "color: red;padding-top:10px;font-size:20px; margin-top:-10px;">Nepal Oil Corporation Ltd.</h1>
                </div>   

                <div>
                        <h5 style="margin-top:-23px;font-family:Arial NARROW;margin-left:70px;">Overtime Claim for <?php echo $detail['MONTH_DESC']?></h5>
                </div>
        </td>
            <td style='width:50%;margin-left:10%;'>
            <div class = "col-sm-12" style="margin-top:-10px;margin-left: 300px;">
                        <div>
                            <h3 class ="col-sm-2" style="font-size:11px;font-family:CALIBRI;width: 100%;margin-top:-10px;">Employee Code: <?php echo $subDetails[0]['EMPLOYEE_CODE']; ?> </h3>
                            <h3 class ="col-sm-2" style="font-size:11px;font-family:CALIBRI;width: 100%;margin-top:-10px;">Employee Name: <?php echo $subDetails[0]['FULL_NAME']; ?></h3>
                            <h3 class ="col-sm-2" style="font-size:11px;font-family:CALIBRI;width: 100%;margin-top:-10px;">Functional level: <?php echo $subDetails[0]['FUNCTIONAL_LEVEL_EDESC']; ?> </h3>
                            <h3 class ="col-sm-2" style="font-size:11px;font-family:CALIBRI;width: 100%;margin-top:-10px;">Office:  <?php echo $subDetails[0]['LOCATION_EDESC'];?></h3>
                        </div>
                    </div>
        </td>
        </tr>
        </table>
        
        <table id = "overtimeDetail" width="100%" align="center" class="customTable div-font-10" style="font-size:9px; border: 2px solid black; border-collapse: collapse; font-family:CALIBRI;">
                <thead>
                    
                    <div class = "col-sm-12" style="margin-top:-20px;margin-bottom:-20px;">
                        <div style = "display: flex;font-family:CALIBRI;">
                            <h3 class ="col-sm-2" style="font-size:11px;width: 100%;">Total OT Days: <?php echo $detail['TOTAL_APP_OT_DAYS']; ?> </h3>
                            <h3 class ="col-sm-2" style="margin-left: 50px;font-size:11px;font-family:CALIBRI;width: 100%;">Total Lunch Allowance: <?php echo $detail['TOTAL_APP_LUNCH_ALLOWANCE']; ?></h3>
                            <h3 class ="col-sm-2" style="margin-left: 50px;font-size:11px;font-family:CALIBRI;width: 100%;">Total Night Allowance: <?php echo $detail['TOTAL_APP_NIGHT_ALLOWANCE']; ?> </h3>
                            <h3 class ="col-sm-2" style="margin-left: 50px;font-size:11px;font-family:CALIBRI;width: 100%;">Total Locking Allowance:  <?php echo $detail['TOTAL_APP_LOCKING_ALLOWANCE'];?></h3>
                        </div>
                    </div>
                        <br>
                        <tr>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Day Detail</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Attendance Date</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Attendance Date(BS)</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Ot remarks</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">In time</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Out time</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Total Hour</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Overtime Hour</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Overtime Days</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Lunch Allowance</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Night Allowance</th>
                            <th style=" border: 1px solid black; border-collapse: collapse;">Locking Allowance</th>
                        </tr>
                </thead>
                <tbody>


                    
                </tbody>
            </table>
            <?php 
            if( $detail['STATUS'] != 'Approved'){
                ?>
            <div class = "col-sm-12">
                <br>
                <div style="display:flex;">
                    <h3 class = "col-sm-2" style="text-decoration-line: overline;">Signature</h3>
                    <h3 class = "col-sm-2" style="text-decoration-line: overline; margin-left: 450px;">Recommender</h3>
                    <h3 class = "col-sm-2" style="text-decoration-line: overline; margin-left: 450px;">Approver</h3>

                </div>
            </div>
            <?php } ?>
            <br>

        </div>
        
    </div>
