<link href="<?= $this->basePath('assets/global/plugins/hide-show-password/css/example.wink.css') ?>" rel="stylesheet" type="text/css"/>
<?php

$this->headScript()->appendFile($this->basePath('js/recruitment/userinformation/edit.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/hide-show-password/hideShowPassword.min.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'usersetup-form');
$form->setAttribute('id', 'usersetup-form');


$userId = $form->get('userId');
$userName = $form->get('userName');
$password = $form->get('password');
$repassword = $form->get('repassword');
$firstName = $form->get('firstName');
$middleName = $form->get('middleName');
$lastName = $form->get('lastName');
$mobileNo = $form->get('mobileNo');
$emailId = $form->get('emailId');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('userinformation', ['action' => 'edit', 'id' => $id]));
$form->prepare();
?>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.checkUserName = '<?= $this->url("userinformation", ["action" => "checkUserName"]) ?>';
    document.editAction = '<?= $this->url("userinformation", ["action" => "edit", 'id' => $id]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\userinformation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Edit User
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <p>Current Password: <?php echo $passwordDtl ?></p>
            <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>

                    <?php print $this->formElement($userId); ?>

                    <div class="row">   

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($firstName->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($firstName); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($firstName); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($firstName, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($middleName->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($middleName); ?>
                                <?php print $this->formElement($middleName); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($middleName, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($lastName->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($lastName); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($lastName); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($lastName, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($emailId->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($emailId); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($emailId); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($emailId, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($mobileNo->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($mobileNo); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($mobileNo); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($mobileNo, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group<?= empty($userName->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($userName); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($userName); ?>
                                <span id="userNameAvailability"></span>
                            </div>
                            <?php print $this->formElementErrors()->render($userName, ['class' => 'help-block error']); ?>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="form-password">Password</label>
                                <span class="required" aria-required="true">*</span>
                                <input name="password" required="required" id="form-password" class="form-password form-control" type="text" value="<?php echo $passwordDtl; ?>">
                                <?php print $this->formElementErrors()->render($password, ['class' => 'help-block error']); ?>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="form-password">Re-Enter Password</label>
                                <span class="required" aria-required="true">*</span>
                                <input name="repassword" required="required" id="form-repassword" class="form-repassword form-control" type="text" value="<?php echo $passwordDtl; ?>">
                            </div>
                        </div>
                    </div>         
                    <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
    </div>
</div>