<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/recruitment/userinformation/index.js'));
?>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<script>
    document.editLink = '<?= $this->url("userinformation", ["action" => "edit"]) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\userinformation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="portlet light bg-inverse">
    <div class="row margin-top-10">

        <div class="col-sm-offset-8 col-sm-4">

            <button id="search" class="btn btn-default btn-sm pull-right">
                Search
                <i class="fa fa-search"></i>
            </button>

        </div>
    </div>
</div>

<div class="margin-top-50">
    <div id="userTable">
    </div>
</div>