<?php
$this->headScript()->appendFile($this->basePath('js/setup/insurance/add.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'insurance-form');

$insuranceCode = $form->get('insuranceCode');
$insuranceEname = $form->get('insuranceEname');
$typeId = $form->get('type');
$open = $form->get('open');
$serviceType = $form->get('serviceType');
$month = $form->get('month');
$flatAmt = $form->get('flatAmt');
$eligibleAfter = $form->get('eligibleAfter');
$remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$form->setAttribute('action', $this->url('insurance', ['action' => 'add']));
$form->prepare();
?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i>
                    Add New Insurance
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($insuranceCode->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($insuranceCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($insuranceCode); ?>
                            <?php print $this->formElementErrors()->render($insuranceCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($insuranceEname->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($insuranceEname); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($insuranceEname); ?>
                            <?php print $this->formElementErrors()->render($insuranceEname, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($typeId->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($typeId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($typeId); ?>
                            <?php print $this->formElementErrors()->render($typeId, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($open->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($open); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($open); ?>
                            <?php print $this->formElementErrors()->render($open, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <label>Service Type</label>
                        <select class="form-control" name="serviceType" id="serviceType">
                            <?php  foreach($serviceList as $key => $value) {  ?>
                            <option value='<?=$key?>'><?=$value?></option>
                            <?php } ?> 
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group <?= empty($eligibleAfter->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($eligibleAfter); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($eligibleAfter); ?>
                            <?php print $this->formElementErrors()->render($eligibleAfter, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliEligibleAfter">&nbsp;</label>
                            <div class="input-group">
                                <input type="text" name="nepaliEligibleAfter" id="nepaliEligibleAfter" placeholder="Date in Nepali"
                                    class="form-control" value="">
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class=" row">
                    <div id="month" class="form-group col-sm-4">
                        <label>Month</label>
                        <span class="required" aria-required="true">*</span>
                        <select class="form-control" name="month" id="month">
                            <?php  foreach($monthList as $key => $value) {  ?>
                            <option value='<?=$key?>'><?=$value?></option>
                            <?php } ?> 
                        </select>
                    </div>
                    <div id="flat" class="col-sm-4">
                        <div class="form-group <?= empty($flatAmt->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($flatAmt); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($flatAmt); ?>
                            <?php print $this->formElementErrors()->render($flatAmt, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($remarks->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($remarks); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <?php print $this->formSubmit($submit); ?>
                <?php print $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>