<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/search.js'))
    ->appendFile($this->basePath('js/transfer-settlement/transfer-settlement-apply/index.js'));

?>

<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.viewLink = '<?= $this->url("transferSettlementStatus", ["action" => "expenseDetail"]) ?>';
    document.editLink = '<?= $this->url("travelRequest", ["action" => "edit"]) ?>';
    document.editTravelLink = '<?= $this->url("travelRequest", ["action" => "editTravel"]) ?>';
    document.deleteLink = '<?= $this->url("travelRequest", ["action" => "delete"]) ?>';
    document.expenseAddLink = '<?= $this->url("transferSettlementApply", ["action" => "expenseAdd"]) ?>';
    document.jvAddLink = '<?= $this->url("travelRequest", ["action" => "jvAdd"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}

?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="portlet light bg-inverse hris-filter-container">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
           
         

                

    
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o" ></i> 
                            Export to Excel 
                        </a>
                    </li>
                    <li >
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o" ></i> 
                            Export to PDF 
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>


    <div class="portlet-body">
        <div class="row">
  
            <input type="hidden" id="empId" value="<?php echo $employeeId; ?>"/>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="startDate">Start Date</label>
                            <input type="text" id="startDate" name="startDate"  class="form-control reset-field"/>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliStartDate">&nbsp;</label>
                            <input type="text" id="nepaliStartDate" name="nepaliStartDate"  class="form-control reset-field"/>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="endDate">End Date</label>
                            <input type="text" id="endDate" name="endDate"  class="form-control reset-field"/>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliEndDate">&nbsp;</label>
                            <input type="text" id="nepaliEndDate" name="nepaliEndDate"  class="form-control reset-field"/>
                        </div>

                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="eventDate">Event Date</label>
                            <input type="text"  id="eventDate" name="eventDate"  class="form-control reset-field"/>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliEventDate">&nbsp;</label>
                            <input type="text"  id="nepaliEventDate" name="nepaliEventDate" class="form-control reset-field"/>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <label>Employee</label>
                        <select multiple class="form-control reset-field" name="employee" id="employeeId">
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-8">
                <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                    Reset
                    <i class="fa fa-refresh"></i>
                </button>
                <label height="45"></label>
                <button  id="search" class="btn btn-default btn-sm pull-right">
                    Search
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="margin-top-20">
    <div id="table">
    </div>
</div> 