<?php
$this->headLink()
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()
    ->appendFile($this->basePath('dropzone/dropzone.min.js'));
$this->headScript()->appendFile($this->basePath('js/dartachalani/darta-chalani/dispatchedView.js'));

?>
<script>
    document.pullFilesbyId = '<?php echo $this->url('dartachalani', ['action' => 'pullFilesbyId']); ?>';
    document.pullDispatchFilebyId = '<?php echo $this->url('dartachalani', ['action' => 'pullDispatchFilebyId']); ?>';
    document.id = <?=json_encode($id)?>;
    document.uploadUrl = '<?= $this->url('dartachalani', ['action' => 'fileUpload']); ?>';
    document.pushFileLink = '<?php echo $this->url('dartachalani', ['action' => 'pushDispatchedFile']); ?>';
    document.getHistoryLink = '<?= $this->url('dartachalani', ['action' => 'dispatchDoc', 'id' => $id]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Branch')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-handshake-o"></i>
                    Dispatched Document
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body" class="view">
                <?php print $this->form()->openTag($form); ?>
                <div class=" row">
                    <div class="col-sm-3">
                        <label><b>Letter Number:</b></label>
                        <label><?php echo $data[0]['LETTER_NUMBER'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>From Department:</b></label>
                        <label><?php echo $data[0]['DEPARTMENT_NAME'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>Description:</b></label>
                        <label><?php echo $data[0]['DESCRIPTION'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>To Office:</b></label>
                        <label><?php echo $data[0]['OFFICE_EDESC'] ?></label>
                    </div>
                </div>
                <div class="row margin-top-30">
                    <div class="col-sm-3">
                        <label><b>Received Date:<b></label>
                        <label><?php echo $data[0]['DOCUMENT_DATE'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>Letter Reference Number:</b></label>
                        <label><?php echo $data[0]['LETTER_REF_NO'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>Response:</b></label>
                        <label> <?php echo $data[0]['RESPONSE_FLAG'] ?></label>
                    </div>
                    <div class="col-sm-3">
                        <label><b>Dispatched Date:</b></label>
                        <label> <?php echo $data[0]['DISPATCH_DATE'] ?></label>
                    </div>
                </div>
                <div class="row margin-top-30">
                    <div class=" col-md-6 form-group">
                        <table id="fileDetailsTbl" class="table">
                            <tr>
                                <th>Document</th>
                                <th>&nbsp;</th>
                                <!-- <th>Action</th> -->
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-3">
                        <!-- <button id="addDocument" type="button" class="btn btn-primary">
                            Add
                        </button> -->
                    </div>
                </div>

                <?php print $this->form()->closeTag(); ?>
            </div>
            <div id="table" ></div>
        </div>
    </div>
</div>
</div>
</div>


<!--bootstrap modal-->
<div id="documentUploadModel" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Document Upload</h4>
            </div>
            <div class="modal-body">
                <div class="modal-body" id="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!--<div id="dropZoneContainer" >-->
                            <div id="dropZoneContainer"  class="dropzone">
                            </div>
                            <div id="uploadErr">Please upload Image.</div>
                        </div>
                    </div>
                </div> 
            </div>

        </div>
        <div class="modal-footer">
            <button id='uploadSubmitBtn' class="btn btn-primary" type="button" >OK</button>
            <button id='uploadCancelBtn' class="btn btn-warning" type="button" >Cancel</button>
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        </div>
    </div>
</div>