<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
    ->appendFile($this->basePath('js/dartachalani/offices/add.js'));



$form->setAttribute('role', 'form');
$form->setAttribute('id', 'Offices');

$officeCode = $form->get('officeCode');
$officeEDESC = $form->get('officeEDESC');
$officeNDESC = $form->get('officeNDESC');
$status = $form->get('status');
$remarks = $form->get('remarks');


$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$form->setAttribute('action', $this->url('offices', ['action' => 'edit',  'id' => $id]));
$form->prepare();

?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Branch')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i>
                    Add New Office
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($officeCode->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($officeCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($officeCode); ?>
                            <?php print $this->formElementErrors()->render($officeCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>


                    <div class="col-sm-2">
                        <div class="form-group <?= empty($officeEDESC->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($officeEDESC); ?>
                            <?php print $this->formElement($officeEDESC); ?>
                            <?php print $this->formElementErrors()->render($officeEDESC, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($officeNDESC); ?>
                            <?php print $this->formElement($officeNDESC); ?>
                            <?php print $this->formElementErrors()->render($officeNDESC, ['class' => 'help-block error']); ?>
                        </div>  
                    </div>
                </div>
            

            

                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($remarks->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                

                
                <?php print $this->formSubmit($submit); ?>
                <?php print $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

