<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/setup/training/add.js'));


$expenseName = $form->get('expenseName');
$accountCode = $form->get('accountCode');


// $endDate = $form->get('endDate');
// $duration = $form->get('duration');
// $instructorName = $form->get('instructorName');
// $trainingType = $form->get('trainingType');
// $trainingType->setValueOptions($trainingTypeList);
// $instituteName = $form->get('instituteId');
// $instituteName->setValueOptions($instituteNameList);
// $dailyTrainingHour = $form->get('dailyTrainingHour');
// $showAsTraining = $form->get('showAsTraining');
// $role = $form->get('role');
// $level = $form->get('level');

// $companyId = $form->get('companyId');
// $companyId->setValueOptions($companies);
//
// $isWithinCompany = $form->get('isWithinCompany');

$submit = $form->get('submit');
$form->setAttribute('action', $this->url('trainingAccountMap', ['action' => 'add']));
$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\training')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($expenseName); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($expenseName); ?>
                            <?php print $this->formElementErrors()->render($expenseName, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($accountCode); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($accountCode); ?>
                            <?php print $this->formElementErrors()->render($accountCode, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
