<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));


$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/angular.min.js'))
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/calculate-overtime/index.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/AttendanceManagement/calculate-overtime/calculate.js'));
?>

<script>
    document.ids =<?php echo json_encode(["statusId" => "All", "employeeTypeId" => "-1", "fromDate" => "", "nepaliFromDate" => "", "toDate" => "", "nepaliToDate" => ""]) ?>;
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.pullAttendanceWidOvertimeListLink = '<?php echo $this->url("calculateOvertime", ["action" => "pullAttendanceWidOvertimeList"]); ?>';
    document.pullInOutTimeLink = '<?php echo $this->url("calculateOvertime", ["action" => "pullInOutTime"]); ?>';
    document.otreadwfilterLink = '<?php echo $this->url("calculateOvertime", ["action" => "otreadwfilter"]); ?>';
    document.calculateLink = '<?php echo $this->url("calculateOvertime", ["action" => "calculate"]); ?>';
    document.otreadLink = '<?php echo $this->url("calculateOvertime", ["action" => "otread"]); ?>';
    document.acl =<?php echo json_encode($acl); ?>;
    document.employeeDetail =<?php echo json_encode($employeeDetail); ?>;
    document.viewLink = '<?= $this->url("calculateOvertime", ["action" => "viewotd"]) ?>';
    document.isotCalc = '<?= $this->isotCalc ?>';
    document.deleteOTDataLink = '<?php echo $this->url("calculateOvertime", ["action" => "deleteOTData"]); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\calculateOvertime')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div ng-app="hris" ng-controller="attendanceWidOTListController">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Search Overtime Records</span>
            </div>
            <div class="tools">
                <a href="" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <a href="javascript::" class="btn default btn-sm" data-toggle="modal" data-target="#myModal">
                    <i class="fa fa-plus-square icon-black"></i> Calculate Overtime </a>
                <!-- <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="export">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                    </ul>
                </div> -->
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Company</label>
                    <select multiple class="form-control" name="company" id="companyId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Branch</label>
                    <select multiple class="form-control" name="branchId" id="branchId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designationId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Location</label>
                    <select multiple class="form-control" name="locationId" id="locationId">
                    </select>
                </div> 
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-2">
                    <label>Service Type</label>
                    <select multiple class="form-control" name="serviceType" id="serviceTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Service Event Type</label>
                    <select multiple class="form-control" name="serviceEventType" id="serviceEventTypeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Current Fiscal Year</label>
                    <?php print $this->formElement($yearsotRead); ?>
                </div>
                <div class="col-sm-2">
                    <label>Month</label>
                    <?php print $this->formElement($monthsotRead); ?>
                </div>
            </div>
            <div class="row margin-top-10">
                <div class="col-sm-12 ">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button ng-click="view()" id="viewAttendanceList" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                    <button id="deleteOTData" class="btn btn-default btn-sm pull-right">
                        Reset Overtime Calculation
                        <i class="fa fa-refresh"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="attendanceWidOTTable">
    </div>

    <div id="calcOTDetailsTable">
    </div>

    <script id="rowTemplate" type="text/x-kendo-tmpl">
        <tr>
        <td>
        #: (IN_REMARKS == null) ? '-' : IN_REMARKS #
        </td>
        <td>
        #: (OUT_REMARKS == null) ? '-' : OUT_REMARKS #
        </td>
        <td>
        <ul id="branchList">  
        #  ln=DETAILS.length #
        #for(var i=0; i<ln; i++) { #
        <li>
        #=i+1 #) #=DETAILS[i].START_TIME # - #=DETAILS[i].END_TIME #
        </li>
        #}#
        </ul>
        </td>
        <td>
        <ul id="branchList">  
        #  ln=DETAILS.length #
        #for(var i=0; i<ln; i++) { #
        <li>
        #=i+1 #) #=DETAILS[i].TOTAL_HOUR #
        </li>
        #}#
        </ul>
        </td>
        </tr>
        <tr class="k-alt">
        <td colspan="3">
        <span class="pull-right">Total Hour</span>
        </td>
        <td> #: (OVERTIME_IN_HOUR == null) ? '' : OVERTIME_IN_HOUR #</td>
        </tr>
    </script>

    <div class="modal fade calculateOvertimeFormModal" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Please Select Year and Month</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="height:14px;">Year</label>
                                <?php print $this->formElement($allyears); ?>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label style="height:14px;">Month</label>
                                <?php print $this->formElement($allmonths); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="readOvertime" class="btn btn-green">Read</button>
                    <button type="button" id="calcOvertime" class="btn btn-green">Calculate</button>
                </div>
            </div>
        </div>
    </div>

</div>