<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>   
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
        
    </script>
<?php } ?>
<?php
$this->headScript()
        ->appendFile($this->basePath('js/manager-service/transferSettlement-approve/expense-view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$jvNumber = $form->get('jvNumber');
$chequeNumber = $form->get('chequeNumber');
$bank = $form->get('bank');


$recommendedRemarks = $form->get('recommendedRemarks');
$recommendedRemarks->setAttributes(["disabled" => "disabled"]);
$approvedRemarks = $form->get('approvedRemarks');
$approvedRemarks->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'APPROVE');

$form->setAttribute('action', $this->url('transferSettlementApprove', ['action' => 'jvAdd', 'id' => $id, 'role' => $serialNumber]));


$form->prepare();
print $this->form()->openTag($form);
?>

<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.pullFilebyId = '<?php echo $this->url('transferSettlementApprove', ['action' => 'pullFilebyId']); ?>';
    document.pushDCFileLink = '<?php echo $this->url('transferSettlementApprove', ['action' => 'pushDCFileLink']); ?>';
    document.uploadUrl = '<?= $this->url("transferSettlementApprove", ["action" => "fileUpload"]); ?>';
    document.id = '<?php echo $id; ?>';
    document.serialNumber = '<?php echo $serialNumber; ?>';
</script>
<div class="row margin-top-20">  
    <div class="col-sm-12">    
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Transfer Settlement Request
                </div>
            </div>
            <div class="portlet-body div-font-11">
            <form name="jobHistoryForm" id="jobHistory-form"  method="post">
            <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="purpose">Start Date :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['START_DATE']; ?>" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="advanceAmount">End Date :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['END_DATE']; ?>" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="departure">Event Date :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['EVENT_DATE'] ?>"  class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                           <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                                <table>
                                    <tr>
                                        <td width="40%">
                                            <label for="destination">To Branch :</label> 
                                        </td>
                                        <td>
                                            <input type="text" disabled="disabled" value="<?php echo $detail['TO_BRANCH_NAME'] ?>" class="form-control">
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                                <table>
                                    <tr>
                                        <td width="40%">
                                            <label for="destination">Status:</label> 
                                        </td>
                                        <td>
                                            <input type="text" disabled="disabled" value="<?php echo $allDetails[0]['STATUS_DETAIL'] ?>" class="form-control">
                                        </td>
                                    </tr>
                                </table>
                            </div>
                    </div>
                
                    <div class="row">
                           <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                                <table>
                                    <tr>
                                        <td width="40%">
                                            <label for="jvNumber">Jv Number :</label> 
                                        </td>
                                        <td>
                                            <input type="text"  class="form-control" name="jvNumber" value="<?php echo $allDetails[0]['JV_NUMBER']; ?>">
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                                <table>
                                    <tr>
                                        <td width="40%">
                                            <label for="chequeNumber">Cheque Number:</label> 
                                        </td>
                                        <td>
                                            <input type="text"  class="form-control" name="chequeNumber" value="<?php echo $allDetails[0]['CHEQUE_NUMBER']; ?>">
                                        </td>
                                    </tr>
                                </table>
                            </div>

                            <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                                <table>
                                    <tr>
                                        <td width="40%">
                                            <label for="bankId">Bank Name:</label> 
                                        </td>
                                        <td>
                                                <select name="bankId" id="bankId" required="required" class="form-control">
                                                    <option value=""  selected="">Please select</option>
                                                    <?php foreach ($bankName as $key => $value) {
                                                        $selected = ($key == $allDetails[0]['BANK_ID']) ? "selected" : ""; ?>
                                                        <option  <?=$selected?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                                    <?php } ?>
                                                </select>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            
                    </div>


                <?php if($allDetails){ ?>
                <div class="margin-top-10 scrollbar-horizantal" id="domesticConfigTable">
                    <div class="row" >
                        <div style="margin-left: 20px" >
                            <table id="domesticConfigTable" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th colspan="12" style="text-align:center; font-weight:bold; font-size:15px;">Transfer Details</th>
                                    </tr>
                                    <tr> 
                                        <th rowspan = "2">Family Member</th>
                                        <th rowspan = "2">Full Name</th>
                                        <th rowspan="2">Departure Date</th>       
                                        <th colspan="2">Location</th>            
                                        <!-- <th rowspan="2">Arrives</th> -->
                                        <th rowspan="2">No. of Days</th> 
                                        <th rowspan="2">Amount</th>
                                        <!-- <th rowspan="2">Total</th>     -->
                                        <th colspan="5">Mode of Transportation</th> 
                                        <th colspan="2">Petty Expenses</th> 
                                        <th rowspan="2">Purpose</th> 
                                        <th rowspan="2">Remarks</th>  
                                        <th rowspan="2">Total All Column</th> 
                                    </tr>
                                    <tr>       
                                        <th>From</th>       
                                        <th>To</th>
                                        <th>On foot, Train, Vehicle, Airplane, Cruise etc.</th>       
                                        <th>Class</th>   
                                        <th>Rate</th>       
                                        <th>Miles</th>
                                        <th>Rate</th> 
                                        <th>Details</th>
                                        <th>Total</th>          
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($allDetails as $domesticExpenseDtlRow) { ?>
                                        <tr>
                                            <td>
                                                <div style="width:90px">
                                                    <?php if($domesticExpenseDtlRow['FOR_FAMILY'] == 'Y'){ ?>
                                                    <input type="checkbox" id="familyMember" name="familyMember" disabled  checked  >
                                                        <?php }else{ ?>
                                                    <input type="checkbox" id="familyMember" name="familyMember" disabled   >
                                                    <?php } ?>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:90px">
                                                    <input type="hidden" value="<?= $domesticExpenseDtlRow['TRANSFER_SETTLEMENT_ID']; ?>"  readonly="readonly" name="transferSettlementId[]"/>
                                                    <input style="width:100%" type="text" name="familyName[]"  class="familyName"  value="<?= $domesticExpenseDtlRow['FAMILY_NAME']; ?>" readonly="readonly">       
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:90px">
                                                    <input style="width:90px" type="text" value="<?= $domesticExpenseDtlRow['FROM_DATE']; ?>"  readonly="readonly" name="depDate[]"/>
                                                    <!-- <input type="text" name="depDate[]"  class="depDate"> -->
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:90px">
                                                    <input style="width:90px" type="text" value="<?= $domesticExpenseDtlRow['DEPARTURE']; ?>"  readonly="readonly" name="locFrom[]"/>       
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:90px">
                                                    <input style="width:90px" type="text" value="<?= $domesticExpenseDtlRow['DESTINATION']; ?>"  readonly="readonly" name="locto[]"/>
                                                    <!-- <input style="width:100%" type="text" name="locto[]"  class="locto">        -->
                                                </div>
                                            </td>      
                                            <td>
                                                <div style="width:50px">
                                                        <input style="width:50px" type="text" value="<?= $domesticExpenseDtlRow['TRAVELLED_DAYS']; ?>"  readonly="readonly" name="noOfDays[]"/>
                                                    <!-- <input style="width:100%" type="number" readonly name="noOfDays[]" required="required"  class="noOfDays">        -->
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['TOTAL_TADA_AMT']; ?>"  readonly="readonly" name="transport[]"/>
                                                </div>
                                            </td>
  
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['TRANSPORTATION']; ?>"  readonly="readonly" name="transport[]"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['TRANSPORT_CLASS']; ?>"  readonly="readonly" name="transportClass[]"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['VEHICLE_EXPENSE_AP_AMT']; ?>"  readonly="readonly" name="rate1[]"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['MILES']; ?>"  readonly="readonly" name="miles[]"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <input style="width:120px" type="text" value="<?= $domesticExpenseDtlRow['PLANE_EXPENSE_AP_AMT']; ?>"  readonly="readonly" name="rate2[]"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <textarea rows="4" cols="50" style="width:100%" readonly="otherExpenseDetail" name="otherExpenseDetail[]"><?= $domesticExpenseDtlRow['MISC_EXPENSE_DETAIL']; ?></textarea>
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:80px">
                                                    <input style="width:80px" type="text" value="<?= $domesticExpenseDtlRow['MISC_EXPENSE_AP_AMT']; ?>"  readonly="readonly" name="otherExpenses[]"/>
                                                    <!-- <input style="width:100%" type="number" name="otherExpenses[]"  class="otherExpenses">        -->
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:120px">
                                                    <textarea rows="4" cols="50" style="width:100%" readonly="detPurpose" name="detPurpose[]"><?= $domesticExpenseDtlRow['PURPOSE']; ?></textarea>
                                                </div>
                                            </td>
                                            
                                            <td>
                                                <div style="width:150px">
                                                    <textarea rows="4" cols="50" style="width:100%" readonly="detRemarks" name="detRemarks[]"><?= $domesticExpenseDtlRow['REMARKS']; ?></textarea>
                                                    <!-- <textarea style="width:100%" rows="4" cols="50" name="detRemarks[]"  class="detRemarks"></textarea> -->
                                                </div>
                                            </td>
                                            <td>
                                                <div style="width:80px">
                                                    <input style="width:80px" type="text" value="<?= $domesticExpenseDtlRow['TOTAL']; ?>"  readonly="readonly" name="total[]"/>
                                                    <!-- <input style="width:100%" readonly type="number" name="total[]"  class="total">        -->
                                                </div>
                                            </td>

                                        </tr>
                                    <?php } ?>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>
                                        </td>
                                        <td><b>Grand Total:</b></td>
                                        <td>
                                            <input type="number" value="<?= $grandTotal ?>"  readonly="readonly" id="sumAllTotal" step="0.01" min="0" readonly="readonly" style="width: 80px;" />
                                        </td>
                                        <td>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
                <?php } ?>
            <br><br>
                <table id="goodsTransportDetailTable" class="table table-bordered">
                        <thead>
                            <tr>
                                <th colspan="12" style="text-align:center; font-weight:bold; font-size:15px;">Goods Transport Detail</th>
                            </tr>
                            <tr>
                                <th>Weight of Goods (K.G.)</th>
                                <th>Price of Transportation</th>      
                                        
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div style="width:100%">
                                    <input style="width:100%" type="number" value="<?= $allDetails[0]['WEIGHT']; ?>"  readonly="readonly" name="weightOfGoods[]" class="weightOfGoods"/>
      
                                    </div>
                                </td>
                                <td>
                                    <div style="width:100%">
                                    <input style="width:100%" type="number" value="<?= $allDetails[0]['WEIGHT_AP_AMT']; ?>"  readonly="readonly" name="priceOfGoods[]" class="priceOfGoods"/>
       
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                
                <div class= "row">
                    <div class=" col-md-6 form-group">
                        <table id="fileDetailsTbl" class="table">
                            <tr>
                                <th>Document</th>
                                <th>&nbsp;</th>
                                <!-- <th>Action</th> -->
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-3">
                        <!-- <button id="addDocument" type="button" class="btn btn-primary">
                            Add
                        </button> -->
                    </div>
                </div>
                <div class="submit_button" style="margin-top:2%;">
                        <button class="btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="submitBtn" name="submit" type="submit">
                            SUBMIT
                            <i class="fa fa-edit"></i>
                        </button>    
                    </div>
                                         </form>
        </div>
    </div>
</div>
