<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
    // ->appendFile($this->basePath('js/recruitment/application/search.js'))
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/js-xlsx-master/dist/xlsx.full.min.js'))
    ->appendFile($this->basePath('js/recruitment/venue/venue-assign.js'));
// ->appendFile($this->basePath('js/recruitment/application/view.js'));
?>

<script>
    document.editLink = '<?= $this->url("venue", ["action" => "venueAssignEdit"]) ?>';
    document.uploadUrl = '<?php echo $this->url("venue", ["action" => "excelUpload"]); ?>';
</script>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="portlet light bg-inverse">
    <div class="row margin-top-10">

        <a href="<?= $this->url('venue', ['action' => 'venueAssignAdd']) ?>" class="btn default btn-sm">
            <i class="fa fa-plus-square icon-black"></i> Assign Venue
        </a>

        <div class="col-sm-offset-8 col-sm-4">

            <button id="search" class="btn btn-default btn-sm pull-right">
                Search
                <i class="fa fa-search"></i>
            </button>

        </div>
    </div>
</div>

<div class="margin-top-50">
    <div id="venueAssignTable">
    </div>
</div>