<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
    ->appendStylesheet($this->basePath('css/custom.css'))
    ->appendStylesheet($this->basePath('css/nepali.datepicker.v4.0.min.css'));;

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/js-xlsx-master/dist/xlsx.full.min.js'))
    ->appendFile($this->basePath('js/recruitment/venue/venue-assign.js'))
    ->appendFile($this->basePath('js/nepali.datepicker.v4.0.min.js'));
?>

<?php

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'venueAssignForm');

$venueSetupId = $form->get('venueSetupId');
$venueSetupId->setValueOptions($venueList);

$startTime = $form->get('startTime');
$endTime = $form->get('endTime');

$venueAssignId = $form->get('venueAssignId');

$examType = $form->get('examType');
$examType->setValueOptions([
    'FIRST_PAPER' => 'First Paper',
    'SECOND_PAPER' => 'Second Paper',
    'INTERVIEW' => 'Interview',
]);

$status = $form->get('status');
$status->setValueOptions([
    'E' => 'Enabled',
    'D' => 'Disabled',
]);

$examDate = $form->get('examDate');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('venue', ['action' => 'venueAssignEdit', 'id'=>$id]));
$form->prepare();
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\venue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Edit Venue Assign
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>
                    <div class="row">   

                        <?php print $this->formElement($venueAssignId); ?>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($venueSetupId); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($venueSetupId); ?>
                                <?php print $this->formElementErrors()->render($venueSetupId, ['class' => 'help-block']); ?>
                            </div>   
                        </div>    

                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($examType); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($examType); ?>
                                <?php print $this->formElementErrors()->render($examType, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <label>Ad Numbers:</label>
                                <select multiple class="form-control" name="vacancies[]" id="vacancies-edit">
                                    <?php foreach($Adno as $ad){ ?>
                                        <option value="<?php echo $ad["VACANCY_ID"]; ?>" <?php if(in_array($ad["VACANCY_ID"], $selectedArray)){ echo "selected"; } ?>>
                                            <?php echo $ad["AD_NO"]; ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($examDate); ?>
                                <?php print $this->formElement($examDate); ?>
                                <?php print $this->formElementErrors()->render($examDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($startTime); ?>
                                <?php print $this->formElement($startTime); ?>
                                <?php print $this->formElementErrors()->render($startTime, ['class' => 'help-block']); ?>
                            </div>
                        </div>  

                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($endTime); ?>
                                <?php print $this->formElement($endTime); ?>
                                <?php print $this->formElementErrors()->render($endTime, ['class' => 'help-block']); ?>
                            </div>
                        </div>

                    </div>          
                    <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
    </div>
</div>