<?php

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'venueForm');

$venueSetupId = $form->get('venueSetupId');
$venueName = $form->get('venueName');

$status = $form->get('status');
$status->setValueOptions([
    'E' => 'Enabled',
    'D' => 'Disabled',
]);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('venue', ['action' => 'venueSetupEdit', 'id' => $id]));
$form->prepare();
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\venue')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>

                    <?php print $this->formElement($venueSetupId); ?>

                    <div class="row">                    
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($venueName); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($venueName); ?>
                                <?php print $this->formElementErrors()->render($venueName, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($status); ?>
                                <?php print $this->formElement($status); ?>
                                <?php print $this->formElementErrors()->render($status, ['class' => 'help-block']); ?>
                            </div>
                        </div>
                    </div>         
                    <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                    <?php
                    print $this->formSubmit($submit);
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
    </div>
</div>