<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
    ->appendStylesheet($this->basePath('css/recruitment.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    // ->appendFile($this->basePath('js/recruitment/application/search.js'))
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/recruitment/application/index.js'));
// ->appendFile($this->basePath('js/recruitment/application/view.js'));
?>

<script>
    document.searchValues = <?php echo json_encode($searchValues); ?>;
    document.viewLink = '<?= $this->url("userapplication", ["action" => "view"]) ?>';
    document.openings = <?php echo json_encode($Openings); ?>;
    document.adno = <?php echo json_encode($Adno); ?>;
    document.Skills = <?php echo json_encode($Skills); ?>;
    document.InclusionList = <?php echo json_encode($InclusionList); ?>;
    document.DepartmentList = <?php echo json_encode($DepartmentList); ?>;
    document.designations = <?php echo json_encode($designations); ?>;
    document.Stages = <?php echo json_encode($Stages); ?>;
    document.bulkStageIdWS = '<?php echo $this->url('userapplication', ['action' => 'bulkStageIdWS']); ?>';
    document.ids = <?php echo json_encode(["OpeningNo" => "", "adnumber" => "", "Gender" => -1, "QualificationId" => "", "designation" => "", "department" => "",]) ?>;
    document.profileurl = '<?= $this->basePath('/'); ?>'; 
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\userapplication')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o"></i>
                            Export to Excel
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-excel-o"></i>
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <input type="hidden" name="employeeId" id="employeeId" value="<?php echo (isset($employeeId)) ? $employeeId : ''; ?>" />
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="OpeningId">Opening Number</label>
                        <!-- <input type="text" id="OpeningNo" name="OpeningNo"  class="form-control reset-field"/> -->
                        <select class="form-control reset-field" name="OpeningNo" id="OpeningNo"></select>
                    </div>
                </div>
                <div class="col-sm-2">
                    <label>Ad Number</label>
                    <select multiple class="form-control" name="adnumber" id="adnumberId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="department">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Designation</label>
                    <select multiple class="form-control" name="designation" id="designation">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label>Gender</label>
                    <select multiple class="form-control" name="gender" id="gender">
                    </select>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="stageId">Stages</label>
                        <select class="form-control" name="stage" id="stage"></select>
                    </div>
                </div>
                <div class="col-sm-2">
                <div class="form-group">
                    <label>Vacancy Type</label>
                    <select class="form-control" name="vacancy_type" id="vacancy_type">
                        <option value="">----</option>
                        <option value="OPEN">OPEN</option>
                        <option value="INTERNAL_FORM">INTERNAL FORM</option>
                        <option value="INTERNAL_APPRAISAL">INTERNAL APPRAISAL</option>
                    </select>
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class="row margin-top-10">
        <div class="col-sm-offset-8 col-sm-4">
            <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                Reset
                <i class="fa fa-refresh"></i>
            </button>
            <button id="search" class="btn btn-default btn-sm pull-right">
                Search
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</div>
<div class="margin-top-20">
    <div id="applicationTable">
    </div>
</div>
<!-- Select Option  -->
<div style="display: none;" class="row margin-top-20" id="acceptRejectDiv">
    <?php if (1 == 1) {  ?>
        <div class="col-sm-2 ">
            <!-- <button id="A" class="btn btn-danger btnApproveReject">Reject</button> -->
        </div>
        <div class="col-sm-2 manualShift">
            <label>Stages</label>
            <select id="StageId" name="StageId">
                <option value="0" selected="selected">---</option>
                <?php foreach ($Stages as $Stage) { ?>
                    <option value="<?= $Stage['REC_STAGE_ID'] ?>"><?= $Stage['STAGE_EDESC'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label for="remarks">Remarks</label>
                <textarea class="form-control" name="remarks" id="remarks" ></textarea>
            </div>
        </div>
        <!-- <div class="col-sm-2 col-sm-offset-8"> -->
        <div class="col-sm-2">
            <button id="P" class="btn btn-primary btnApproveReject pull-right" style="margin-top: 15px">Update Stage</button>
        </div>
    <?php } ?>
</div>
</div>