<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));

$this->headScript()->appendFile($this->basePath('js/SelfService/overtime-claim/add.js'));
?>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('overtimeClaim', ['action' => 'getFiscalYearMonth']); ?>';
    document.validateAttendanceLink = '<?= $this->url("overtimeRequest", ["action" => "validateAttendance"]) ?>';
    document.validateOvertimeDateLink = '<?= $this->url("overtimeRequest", ["action" => "validateOvertimeDate"]) ?>';
    document.validateEmployeeShiftLink = '<?= $this->url("overtimeRequest", ["action" => "validateEmployeeShift"]) ?>';
    document.getAllOvertimeDetailLink = '<?= $this->url("overtimeClaim", ["action" => "getAllOvertimeDetail"]) ?>';
    document.getHolidayDetail = '<?php echo $this->url('overtimeClaim', ['action' => 'getHolidayDetails']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtimeClaim')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<script>
    document.urlOvertime = '<?= $this->url("overtimeRequest", ["action" => "index"]) ?>';</script>
<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export to Excel
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label class="control-label">Year</label>
                    <select class="form-control" id="fiscalYearId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Month</label>
                    <select class="form-control" id="monthId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Total OT Days</label>
                    <input readonly class="form-control" id="totalOtDays" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Total OT Hour</label>
                    <input readonly class="form-control" id="totalOtHour" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Lunch Allowance</label>
                    <input readonly class="form-control" id="lunchExpense" />
                </div>
                
                <?php /* <div class="col-sm-2">
                    <label class="control-label">Month</label>
                    <select class="form-control" id="monthId">
                        <?php $count = 0; foreach($monthList as $k => $v){ $count++; if($count<4){ ?>
                            <option value="<?php echo $k ?>"><?php echo $v ?></option>
                        <?php }} ?>
                    </select>
                </div> */ ?>
            </div>
            <div class="row" style="margin-top:20px;">
                <div class="col-sm-2">
                    <label class="control-label">Night Allowance</label>
                    <input readonly class="form-control" id="nightAllowance" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Locking Allowance</label>
                    <input readonly class="form-control" id="lockingAllowance" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Satta Bida</label>
                    <input readonly class="form-control" id="totalLeave" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Dashain-Tihar Satta</label>
                    <input readonly class="form-control" id="dashainTiharLeave" />
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Total Satta Bida</label>
                    <input readonly class="form-control" id="grandTotalLeave" />
                </div>
                
            </div>
            <div class="row margin-top-30">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>

            
            
            <div id="table" style="margin-top:20px;">
            </div>
            <div style="display: none;" class="row margin-top-20" id="claimBtnDiv" >
                <div class="col-sm-2 ">
                    <button id="btnOvertime" class="btn btn-info btnClassify">Claim Overtime</button>
                </div>
                
                <div class="col-md-6" style="text-align:center;">
                <a class="btn btn-success" id="print"> Print</a>
                </div>
            </div> 
        </div>

        
    </div>
</div>
