<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/overtime-claim/view.js'));

?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\overtimeClaim')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<script>
    document.urlOvertime = '<?= $this->url("overtimeRequest", ["action" => "index"]) ?>';
    document.id = <?=$id?>;
    document.subDetails = <?php echo json_encode($subDetails) ?>;
</script>
<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i>
                                Export to Excel
                            </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-3">
                    <label class="control-label">Employee</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['FULL_NAME']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Date</label>
                    <input disabled type="text" class="form-control" value="<?php echo ($detail['REQUESTED_DT_AD'] . ' A.D.    |    ' . $detail['REQUESTED_DT_BS'].' B.S.')?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Month</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['MONTH_DESC']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Status</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['STATUS']?>">
                </div>
            </div>
            <div class="row" style="margin-top:30px;">
                
                <div class="col-sm-3">
                    <label class="control-label">Requested OT Hours</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_OT_HOURS']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Requested Leave</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_REQ_SUBSTITUTE_LEAVE']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved OT Hours</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_APP_OT_HOURS']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approved Leave</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['TOTAL_APP_SUBSTITUTE_LEAVE']?>">
                </div>
                
            </div>
            <div class="row" style="margin-top:30px;">
                <div class="col-sm-3">
                    <label class="control-label">Recommender</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['RECOMMENDER']?>">
                </div>
                <div class="col-sm-3">
                    <label class="control-label">Approver</label>
                    <input disabled type="text" class="form-control" value="<?php echo $detail['APPROVER']?>">
                </div>
            </div>
            
            <div id="table" style="margin-top:20px;">
            </div>
            <div style="display: none;" class="row margin-top-20" id="claimBtnDiv" >
                <div class="col-sm-2 ">
                    <button id="btnOvertime" class="btn btn-info btnClassify">Claim Overtime</button>
                </div>
            </div> 
        </div>

        
    </div>
</div>
