<?php

$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
    ->appendFile($this->basePath('js/gratuity/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'gratuityCalc-form');
$employeeId = $form->get('employeeId');
$employeeId->setValueOptions($employees);

$extraServiceYear = $form->get('extraServiceYear');
$retirementDate = $form->get('retirementDate');

$submit = $form->get('submit');
$submit->setAttribute('value', 'CALCULATE');

$form->setAttribute('action', $this->url('gratuity', ['action' => 'add']));


$form->prepare();
?>



<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i>
                        Gratuity Calculator
                    </div>
                    <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                    </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($employeeId); ?>
                            <span class="required" aria-required="true">*</span>
                            <select name="employeeId" id="form-employeeId" required="required"  class="form-control">
                                <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                                <?php foreach ($employees as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                                <?php } ?>
                            </select>
                            <?php print $this->formElementErrors()->render($employeeId, ['class' => 'help-block']); ?> 
                        </div>  
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($extraServiceYear); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($extraServiceYear); ?>
                            <?php print $this->formElementErrors()->render($extraServiceYear, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-4">
                        <div class = 'row'>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($retirementDate); ?>
                                    <?php print $this->formElement($retirementDate); ?>
                                    <?php print $this->formElementErrors()->render($retirementDate, ['class' => 'help-block']); ?>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliRetirementDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliRetirementDate" id="nepaliRetirementDate"
                                            class="form-control" value="">
                                    </div>
                                </div>
                            </div> 
                        </div>  
                   </div>
                  
                <?php
                print $this->formSubmit($submit);
                ?>
                

                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    <div>
</div>
