<?php
//Load JS files here
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
    
$this->headScript()
        ->appendFile($this->basePath('js/search.js'))
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/gratuity/index.js'));
?> 

<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.viewLink = '<?= $this->url("incoming-document", ["action" => "view"]) ?>';
    document.editLink = '<?= $this->url("incoming-document", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("incoming-document", ["action" => "delete"]) ?>';
    document.forwardLink = '<?= $this->url("incoming-document", ["action" => "forward"]) ?>';
    document.acknowledgeLink = '<?= $this->url("incoming-document", ["action" => "acknowledge"]) ?>';
    document.getAllIncoming = '<?= $this->url("incoming-document", ["action" => "getAllIncomingData"]) ?>';
    document.getAllIncomingDatabyIdAction = '<?= $this->url("incoming-document", ["action" => "getAllIncomingDatabyId"]) ?>';
    document.getAllGratuityDataAction = '<?= $this->url("gratuity", ["action" => "getAllGratuityData"]) ?>';
    document.endProcess = '<?php echo($endProcess); ?>';
    document.viewLink = '<?= $this->url("gratuity", ["action" => "view"]) ?>';
    document.recalculateLink = '<?= $this->url("gratuity",["action" => "recalculate"])?>';
    document.deleteLink = '<?= $this->url("gratuity",["action" => "deleteGratuity"])?>';

</script>
<div id="incomingDocumentList" >
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a  class="collapse"></a>
                <a  class="fullscreen"></a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('gratuity', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> Calculate </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools<i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> Export to PDF </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <label>Employee</label>
                    <select multiple class="form-control" name="employee" id="employeeId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-30">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="incomingDocumentsTable">
    </div>
</div>