<?php
//Load JS files here
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/SelfService/outgoing-doc/dispatched.js'));
?> 
<script>
    document.viewLink = '<?= $this->url("outgoingdoc", ["action" => "dispatchDoc"]) ?>';
    document.getTableData= '<?= $this->url("outgoingdoc", ["action" => "getTableData"]) ?>';
    document.getSearchDataById= '<?= $this->url("outgoingdoc", ["action" => "getSearchData"]) ?>';
    document.pullFilebyId = '<?php echo $this->url('outgoingdoc', ['action' => 'pullFilebyId']); ?>';

</script>
<div class="margin-top-20">
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Search</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                <a href="" class="fullscreen" data-original-title="" title=""> </a>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools
                        <i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id ="export" class="hris-export-to-excel" hris-export-to-excel-target="branchTable">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> 
                                Export to PDF 
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
            <div class="col-sm-3">
                    <label>Letter No.</label>
                    <input type="text" class="form-control" id="letterNo" name="letterNo">
                </div>
                <div class="col-sm-3">
                    <label>Description</label>
                    <input type="text" class="form-control" id="description" name="description">
                </div>
                <div class="col-sm-3">
                    <label>Recieving Office</label>
                    <select class="form-control" name="toOfficeCode" id="toOfficeCode">
                    <?php  foreach($officeList as $key => $value) {  ?>
                        <option value='<?=$key?>'><?=$value?></option>
                    <?php } ?> 
                    </select>
                    <!-- <input type="text" class="form-control" id="toOfficeCode" name="toOfficeCode"> -->
                </div>
                  
                <div class="col-sm-12">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn" style="margin-top:15px;">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button  id="search" class="btn btn-default btn-sm pull-right" style="margin-top:15px;">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
            </div>
        </div>
            <div id="dispatchedTable">
            </div>
    </div>
</div>