<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/recruitment/onboard/index.js'));
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\userapplication')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<script>
        document.onboardEmployee = '<?php echo $this->url('onboard', ['action' => 'onboardEmployee']); ?>';
</script>
<?php if ($this->messages) { ?>
    <script>
        document.messages = <?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Selected Applicants</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o"></i>
                            Export to Excel
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-excel-o"></i>
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="margin-top-20">
        dfsgh
        <div id="onboardtable">
        </div>
    </div>
    <div style="display: none;" class="row margin-top-20" id="acceptRejectDivOnboard">
    <?php if (1 == 1) {  ?>
        <div class="col-sm-2">
            <button type="button" id="P" class="btn btn-primary btnApproveOnboard pull-right" style="margin-top: 15px">Add Applicant As Employee</button>
        </div>
    <?php } ?>
</div>
</div>
