<?php
$this->headLink()
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('dropzone/dropzone.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/LeaveManagement/substitute-leave/add.js'));

?>
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('substituteLeave', ['action' => 'getFiscalYearMonth']); ?>';
    document.searchValues =<?php echo json_encode($searchValues); ?>;
    document.getWohWodListLink = '<?php echo $this->url('substituteLeave', ['action' => 'getWohWodList']); ?>';
    document.classifyURL = '<?php echo $this->url('substituteLeave', ['action' => 'classify']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\substituteLeave')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>

<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Classify
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label">Employee</label>
                        <select name="employeeId" id="form-employeeId" required="required"  class="form-control">
                            <option value="" disabled="" selected="" class="ng-binding">Please select</option>                           
                            <?php foreach ($employees as $key => $value) { ?>
                                <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Year</label>
                    <select class="form-control" id="fiscalYearId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Month</label>
                    <select class="form-control" id="monthId">
                    </select>
                </div>
                <div class = "col-sm-2">
                    <button id="view" class="btn btn-primary btn-sm pull-right">
                        View
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
            <div id="kendo_table">
            </div> 
            <div style="display: none;" class="row margin-top-20" id="classifyBtnDiv" >
                <div class="col-sm-2 ">
                    <button id="btnOvertime" class="btn btn-info btnClassify">Overtime</button>
                </div>
                <div class="col-sm-2 col-sm-offset-8">
                    <button id="btnSubstituteLeave" class="btn btn-info btnClassify pull-right">Replacement leave</button>
                </div>
            </div> 
        </div>
    </div>
    
</div>
