<?php
//Load JS files here
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
    
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/LeaveManagement/substitute-leave/index.js'));
?> 
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('substituteLeave', ['action' => 'getFiscalYearMonth']); ?>';
    document.getAllSubtituteLeaveDataLink = '<?php echo $this->url('substituteLeave', ['action' => 'getAllSubtituteLeaveData']); ?>';
</script>
<div id="incomingDocumentList" >
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Employees</span>
            </div>
            <div class="tools">
                <a  class="collapse"></a>
                <a  class="fullscreen"></a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('substituteLeave', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools<i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> Export to PDF </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group">
                        <label class="control-label">Employee</label>
                        <select multiple name="employeeId" id="form-employeeId" required="required"  class="form-control">
                            <?php foreach ($employees as $key => $value) { ?>
                                <option value="<?php echo $key; ?>"><?php echo $value; ?></option> 
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Year</label>
                    <select class="form-control" id="fiscalYearId">
                    </select>
                </div>
                <div class="col-sm-2">
                    <label class="control-label">Month</label>
                    <select class="form-control" id="monthId">
                    </select>
                </div>
            </div>
            <div class="row margin-top-30">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="table">
    </div>
</div>