<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
                    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancy/dropdown.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'optionsform');

$OptionsEdesc = $form ->get('OptionsEdesc');
$OptionsNdesc = $form ->get('OptionsNdesc');
$Remarks = $form->get('Remarks');
$submit = $form->get('submit');
$UploadFlag = $form ->get('UploadFlag');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('options', ['action' => 'add']));

$form->prepare();
?>
<script>
    
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script> 

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancy')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?> 
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
            </div>
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="row">           
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($OptionsEdesc); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($OptionsEdesc); ?>
                            <?php print $this->formElementErrors()->render($OptionsEdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($OptionsNdesc); ?>
                            <?php print $this->formElement($OptionsNdesc); ?>
                            <?php print $this->formElementErrors()->render($OptionsNdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($UploadFlag); ?>
                            <div class="md-radio-inline">
                                <?php $customRenderer($UploadFlag); ?>
                            </div>
                            <?php print $this->formElementErrors()->render($UploadFlag, ['class' => 'help-block']); ?>
                        </div>
                    </div>   
                    
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($Remarks); ?>
                            <?php print $this->formElement($Remarks); ?>
                            <?php print $this->formElementErrors()->render($Remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                ?>                
                <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>



