
<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript();
        // ->appendFile($this->basePath('js/recruitment/vacancy/dropdown.js'));
       // ->appendFile($this->basePath('js/recruitment/opening/view.js'));

        
$form->setAttribute('role', 'form');
$form->setAttribute('id', 'optionsform');
$OptionsEdesc = $form ->get('OptionsEdesc');
$OptionsNdesc = $form ->get('OptionsNdesc');
$Remarks = $form->get('Remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

// $form->setAttribute('action', $this->url('vacancy', ['action' => 'action', 'id' => $id]));

$form->setAttribute('action', '');
$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\options')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="col-sm-12">
    <div class="portlet box custom-box">`
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Options Detail
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="border-bottom">
                <div class="row">           
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($OptionsEdesc); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($OptionsEdesc); ?>
                            <?php print $this->formElementErrors()->render($OptionsEdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($OptionsNdesc); ?>
                            <?php print $this->formElement($OptionsNdesc); ?>
                            <?php print $this->formElementErrors()->render($OptionsNdesc, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($Remarks); ?>
                            <?php print $this->formElement($Remarks); ?>
                            <?php print $this->formElementErrors()->render($Remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                </div>              
            </div>
        </div>
    </div>
</div>


<?php
print $this->formSubmit($submit);
print $this->form()->closeTag();
?>

