<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
                    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
                    // ->appendFile($this->basePath('js/recruitment/stage/dropdown.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancyinclusion/edit.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'vacancyinclusion');

$InclusionId = $form->get('InclusionId');
$InclusionId->setValueOptions($InclusionList);
$VacancyId = $form->get('VacancyId');
$VacancyId->setValueOptions($VacancyList);
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', '');
$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script> 

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancyinclusion')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?> 
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Edit Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo (isset($employeeId)) ? $employeeId : ''; ?>"/>
            </div>
                <div class="row">    
                <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($VacancyId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($VacancyId); ?>
                            <?php print $this->formElementErrors()->render($VacancyId, ['class' => 'help-block']); ?>
                        </div>
                    </div>       
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($InclusionId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($InclusionId); ?>
                            <?php print $this->formElementErrors()->render($InclusionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>                    
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
