<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
        ->appendFile($this->basePath('js/Workforce/index.js'))
        ->appendFile($this->basePath('dropzone/dropzone.min.js'));

?>
<script>
    document.branchList = <?= json_encode($branchList); ?>;
    document.positionList = <?= json_encode($positionList); ?>;
    document.groupList = <?= json_encode($groupList); ?>;
    document.serviceList = <?= json_encode($serviceList); ?>;
    document.designationList = <?= json_encode($designationList); ?>;
    document.departmentList = <?= json_encode($departmentList); ?>;
    document.getCurrentStaff = '<?= $this->url("workforce", ["action" => "getCurrentStaff"]) ?>';
    document.getPastValues = '<?= $this->url("workforce", ["action" => "getPastValues"]) ?>';
</script>
<h1>Workforce</h1>
<form name="workforceForm" id="workforceForm"  method="post">
    <div class="col-sm-12">
        <div class=" row">
            <div class="col-sm-2">
                <label for="branch">Branch : </label> 
            </div>
            <div class="col-sm-10" style="margin-left:-70px;">
                <select class='branch' name='branch[]' id='branch'></select>
            </div>
        </div>
        <div class=" row" id='departmentDiv'>
            <div class="col-sm-2"  style="margin-top:30px;">
                <label for="department">Department : </label> 
            </div>
            <div class="col-sm-10" style="margin-top:30px; margin-left:-70px;">
                <select class='department' name='department[]'></select>
            </div>
            
        </div>
        <div class="margin-top-10 scrollbar-horizantal" >
            <div class="row" >
                <div style="margin-left: 20px; margin-top: 20px;" >
                    <table id="workforceTable" class="table table-bordered">
                        <thead>
                            <tr>
                                <th colspan="12" style="text-align:center; font-weight:bold; font-size:15px;">Work Force</th>
                            </tr>
                            <tr>
                                <th rowspan="2">Action</th> 
                                <th rowspan="2">Positions</th> 
                                <th rowspan="2">Locations</th>       
                                <th rowspan="2">Service Type</th>       
                                <th rowspan="2">Designation</th>
                                <th rowspan="2">Quota</th> 
                                <th rowspan="2">Current</th>
                                <th rowspan="2">Vacant</th>        
                                        
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                                <td>
                                    <div style="width:90px">
                                        <select class='position' name='position[]' style="width:100%">
                                        </select>
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <select class='group' name='group[]' >
                                        </select>       
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <select class='service' name='service[]' >
                                        </select>      
                                    </div>
                                </td>
                                <td>
                                    <div style="overflow:hidden">
                                        <select class='designation' name='designation[]' >
                                        </select>
                                    </div>
                                </td>       
                                <td>
                                    <div style="width:80px">
                                        <input style="width:100%" type="number" name="quota[]"   class="quota">       
                                    </div>
                                </td>
                                <td>
                                    <div style="width:80px">
                                        <input style="width:100%" type="number" readonly name="current[]" class="current">       
                                    </div>
                                </td>
                                <td>
                                    <div style="width:80px">
                                        <input style="width:100%" type="number" readonly name="vacant[]"  class="vacant">       
                                    </div>
                                </td> 

                            </tr>
                        </tbody>
                    </table>

                </div>
                <div class="col-md-1">
                    <input class="deatilAddBtn btn btn-default" type="button" value="Add +" style="margin-bottom:20px;">
                </div>

            </div>
        <div>
    </div>
    <div class="submit_button" style="margin-top:2%;">
        <button class="btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="submitBtn" name="submit" type="submit">
            SUBMIT
            <i class="fa fa-edit"></i>
        </button>    
    </div>
</form>
