<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>without bootstrap</title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
  </head>
  <body>
  <div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New EntrySet up's for Admit Card
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <form action="<?php echo  $this->basePath('recruitment/instruction/add')?>" id="instructionform" method="post">
                    <label for="shortdesc"> <strong>Short Description</strong> </label>
                    <div class="form-group">
                        <textarea name="shortdesc" id="summernote" cols="30" ></textarea>
                    </div>
                  
                    <label for="shortdesc"> <strong>Instruction To Be Followed</strong> </label>
                    <div class="form-group">
                        <textarea name="instruction" id="longIns" cols="30" rows="10"></textarea>
                    </div>
                    <div class="form-group">
                    <label for="shortdesc"> <strong>Karyalaya Name</strong> </label> <br>
                        <input type="text" class="form-control" name="karyalaya_name" value="<?php echo $nameCheck ?>">
                    </div>
                    
                      <input type="hidden" id="sdhbvsbd" value="<?php echo strip_tags($shortIns); ?>">
                      <input type="hidden" id="lonfvb" value="<?php echo strip_tags($longIns); ?>">
                    <input type="submit" value="Submit">
                </form>
                
            </div>
        </div>
    </div>
  </div>
    <script>
      var value = $('#sdhbvsbd').val();
     
       $('#summernote').summernote('insertText', value,{
        placeholder: 'Enter Short Description Here',
        tabsize: 2,
        height: 60,
        insertText: "helfdfmvsnf",
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
      var longValur = $('#lonfvb').val();
      $('#longIns').summernote('insertText', longValur,{
        placeholder: 'Enter Short Description Here',
        tabsize: 2,
        height: 60,
        insertText: "helfdfmvsnf",
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
     

    
      
    </script>
  </body>
</html>