<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'))
        ->appendStylesheet('https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css');

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile('https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js');
$this->headScript()
                    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
                    ->appendFile($this->basePath('js/recruitment/opening/add.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancy/dropdown.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'OpeningForm');
$OpeningNo = $form->get('OpeningNo');
$Vacancy_total_no = $form->get('Vacancy_total_no');
$ReservationNo = $form->get('ReservationNo');
$Start_dt = $form->get('Start_dt'); 
$End_dt = $form->get('End_dt');
$Extended_dt = $form->get('Extended_dt'); 
$Instruction_Edesc = $form->get('Instruction_Edesc');
$Instruction_Ndesc = $form->get('Instruction_Ndesc');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('opening', ['action' => 'add']));

$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.pushVacancyFileLink = '<?php echo $this->url('opening', ['action' => 'pushVacancyFileLink']); ?>';
    document.uploadUrl = '<?= $this->url('opening', ['action' => 'fileUpload']); ?>';
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script> 

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\opening')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?> 
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo (isset($employeeId)) ? $employeeId : ''; ?>"/>
            </div>
                <?php
                print $this->form()->openTag($form);
                ?>
 
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($OpeningNo); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($OpeningNo); ?>
                            <?php print $this->formElementErrors()->render($OpeningNo, ['class' => 'help-block']); ?>                            
                        </div>                        
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($Vacancy_total_no); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($Vacancy_total_no); ?>
                            <?php print $this->formElementErrors()->render($Vacancy_total_no, ['class' => 'help-block']); ?>                            
                        </div>                        
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <?php print $this->formLabel($ReservationNo); ?>
                            <!-- <span class="required" aria-required="true">*</span> -->
                            <span class="required" aria-required="true">(optional)</span>
                            <?php print $this->formElement($ReservationNo); ?>
                            <?php print $this->formElementErrors()->render($ReservationNo, ['class' => 'help-block']); ?>                            
                        </div>                        
                    </div>                                      
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($Start_dt); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($Start_dt); ?>
                            <?php print $this->formElementErrors()->render($Start_dt, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliStartDate">&nbsp;</label>
                            <input type="text" name="nepaliStartDate" id="nepaliStartDate"
                                   class="form-control" value="">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($End_dt); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($End_dt); ?>
                            <!-- <span id="errorMsgDate" style="font-size:11px; color:red;"></span> -->
                            <?php print $this->formElementErrors()->render($End_dt, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliEndDate">&nbsp;</label>
                            <input type="text" name="nepaliEndDate" id="nepaliEndDate"
                                   class="form-control" value="">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($Extended_dt); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($Extended_dt); ?>
                            <?php print $this->formElementErrors()->render($Extended_dt, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliExtendedDate">&nbsp;</label>
                            <input type="text" name="nepaliExtendedDate" id="nepaliExtendedDate"
                                   class="form-control" value="">
                        </div>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <Label>Opening Notes In English</Label>
                            <textarea name="Instruction_Edesc" id="summernote" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <Label>Opening Notes In Nepali</Label> <br>
                            <textarea name="Instruction_Ndesc" id="summernote3" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    
                </div>
                <div class="row">
                    <div class=" col-md-6 form-group">
                        <table id="fileDetailsTbl" class="table">
                            <tr>
                                <th>Document</th> 
                                <th>&nbsp;</th>
                                <th>Action</th>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-3">
                        <button id="addDocument" type="button" class="btn btn-primary">
                            Add
                        </button>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                ?>                
                <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
<!--bootstrap modal-->
<div id="documentUploadModel" class="modal fade" role="dialog">
    <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Document Upload</h4>
        </div>
        <div class="modal-body">
            <div class="modal-body" id="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <!--<div id="dropZoneContainer" >-->
                        <div id="dropZoneContainer"  class="dropzone">
                        </div>
                        <div id="uploadErr">Please upload Your File.</div>
                    </div>
                </div>
            </div> 
        </div>
            <div class="modal-footer">
                <button id='uploadSubmitBtn' class="btn btn-primary" type="button" >OK</button>
                <button id='uploadCancelBtn' class="btn btn-warning" type="button" >Cancel</button>
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
            </div>
        </div>
    </div>
</div>