ALTER TABLE HRIS_GL_ENTRY ADD (GL_ENTRY_MASTER_ID INTEGER);


------------------HRIS_GL_MAP-------------------------------------
CREATE TABLE HRIS_GL_MAP(
GL_ID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
MODULE_CODE VARCHAR(255),
OUTGOING_DR_GL VARCHAR(255),
OUTGOING_CR_GL VARCHAR(255),
INCOMING_DR_GL VARCHAR(255),
INCOMING__CR_GL VARCHAR(255),
STATUS CHAR(1),
CREATED_BY NUMBER(7,0),
APPROVED_BY NUMBER(7,0),
APPROVED_DATE DATE,
MODIFIED_BY NUMBER(7,0),
CREATED_DT DATE,
CHECKED_BY NUMBER(7,0),
CHECKED_DT DATE,
MODIFIED_DT DATE,
DELETED_BY NUMBER(7,0),
DELETED_DT DATE,
REMARKS VARCHAR(255)
);

------------------HRIS_GL_MAP-------------------------------------
CREATE TABLE HRIS_PAY_HEADS_MAP(
PHM_ID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
GL_CODE VARCHAR(255),
PAY_HEAD VARCHAR(255),
DR_ACC_CODE VARCHAR(255),
CR_ACC_CODE VARCHAR(255),
STATUS CHAR(1),
CREATED_BY NUMBER(7,0),
APPROVED_BY NUMBER(7,0),
APPROVED_DATE DATE,
MODIFIED_BY NUMBER(7,0),
CREATED_DT DATE,
CHECKED_BY NUMBER(7,0),
CHECKED_DT DATE,
MODIFIED_DT DATE,
DELETED_BY NUMBER(7,0),
DELETED_DT DATE,
REMARKS VARCHAR(255)
);

----------------------------------------
insert into HRIS_PAY_HEADS_MAP values (1, 'GA', 'Grade Amount', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'AL', 'Allowance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'DE', 'Dearness', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'DA', 'Dress Allowance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'HM', 'House Maintenance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'RA', 'Remote area Allowance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'ELD', 'EPF Loan Deduction', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'FA', 'Field Allowance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'TG', 'Technical Grade Amount', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'MT', 'Monthly Income Tax', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'PK', 'Poshak Kharcha', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'DK', 'Dashin Kharcha', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'KK', 'Khaja Kharcha', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'EA', 'EPF Addition', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'ED', 'EPF Deduction', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'BA', 'Basic Arrears', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'DAR', 'Dashain Arrears', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'CV', 'CA Vatta', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'BS', 'Basic Salary', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'CT', 'CIT', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'ND', 'NLK Loan Deduction', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'MS', 'Monthly Social Security Tax', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'PC', 'Pregnancy Care', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'OB', 'Other Benefits', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'HE', 'House Maintenance EWF', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'HCL', 'House Land Purchase Or House Construction Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'HML', 'House Maintenance Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'SAL', 'Social Activity Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'MCL', 'Motorcycle Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'FIL', 'Family Insurance Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'EL', 'Education Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'KKL', 'KKK Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'ML', 'Marriage Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'MTL', 'Modern Technology Purchase Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'VPL', 'Vehicle Purchase Loan', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'MA', 'Medical Allowance', null, null, null, null, null, null, null, null, null, null, null, null, null, null );
insert into HRIS_PAY_HEADS_MAP values ((SELECT MAX(PHM_ID) + 1 FROM HRIS_PAY_HEADS_MAP), 'LE', 'Leave Encashment', null, null, null, null, null, null, null, null, null, null, null, null, null, null );

--update status and created_dt--

update HRIS_PAY_HEADS_MAP set status = 'E', created_dt = current_date; 



---------------------Alter Travel Tables------------------
ALTER TABLE hris_employee_travel_request ADD (EXPENSE_AMOUNT DOUBLE NULL);
ALTER TABLE hris_employee_travel_request ADD (ADJUSTMENT_AMOUNT DOUBLE NULL);
ALTER TABLE hris_employee_travel_request ADD (ADJUSTMENT_FLAG CHAR(1) NULL); 
ALTER TABLE hris_employee_travel_request ADD (VOUCHER_NO VARCHAR(100) NULL);
ALTER TABLE hris_employee_travel_request ADD (VOUCHER_DATE DATE NULL);

--If data type is different that VOUCHER_NO VARCHAR(100)
--ALTER TABLE hris_employee_travel_request ALTER (VOUCHER_NO VARCHAR(100) NULL);


ALTER TABLE HRIS_TRAVEL_EXPENSE ADD (VOUCHER_NO VARCHAR(100) NULL);
ALTER TABLE HRIS_TRAVEL_EXPENSE ADD (VOUCHER_DATE DATE NULL);


CREATE TABLE HRIS_TRAVEL_SETUP
(ADVANCE_AC_CODE VARCHAR2(25) NOT NULL,
PAYABLE_AC_CODE VARCHAR2(25) NOT NULL,
EXPENSE_AC_CODE VARCHAR2(25) NOT NULL,
ADJUSTMENT_AC_CODE VARCHAR2(25) NOT NULL)

INSERT INTO HRIS_TRAVEL_SETUP VALUES ('IE0201000020000', 'IE0201000020000', 'IE0201000020000', 'IE0201000020000');




