<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
                    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancyoptions/add.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancy/dropdown.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'vacancyoptions');

$VacancyId = $form->get('VacancyId');
$VacancyId->setValueOptions($VacancyList);
// $OpeningId = $form->get('OpeningId');
// $OpeningId->setValueOptions($VacancyList);
// $Status = $form ->get('Status');
// $Remarks = $form->get('Remarks');
$submit = $form->get('submit');
$submit->setAttribute('id', 'submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('vacancyoptions', ['action' => 'add']));

$form->prepare();
?>
<script>
    
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.OptionLists = <?= json_encode($OptionList); ?>;
    document.positions = <?= json_encode($positions); ?>;
    document.Quota_open = <?= json_encode($Quota_open); ?>;
    document.Quota_openleft = <?= json_encode($Quota_open_left); ?>;
    document.Quota_internal = <?= json_encode($Quota_internal); ?>;
</script> 

<div class="page-bar">
    
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?> 
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                    <?php
                    print $this->form()->openTag($form);
                    ?>
                    <div class="row">                    
                        <div class="col-sm-2">
                            <div class="form-group">
                                <?php print $this->formLabel($VacancyId); ?>
                                <?php print $this->formElement($VacancyId); ?>
                                <?php print $this->formElementErrors()->render($VacancyId, ['class' => 'help-block']); ?>
                            </div> 
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="positionId">Position : </label>
                                <p id="position"></p>
                            </div> 
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <label for="QuotaOpen">Open Quota :</label>
                                <p id="quotaopen"></p>
                            </div> 
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="QuotaInternal">Internal Quota :</label>
                                <p id="quotaInternal"></p>
                            </div> 
                        </div>
                    </div>
                    
                    <!--Vacancy Options details addition-->
                    <div class="row" >
                        <div class="col-md-11" >
                            <table id="vacancyoptionsDetails" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th colspan="3">Option Details</th>       
                                        <th colspan="2">Amount</th>             
                                        <th colspan="1">Remarks</th>       
                                        <th rowspan="2">Action</th>        
                                    </tr>
                                    <tr>
                                        <th>Options List</th>
                                        <th>Open / Internal</th>
                                        <th>Quota</th>      
                                        <th>Normal Amount</th>
                                        <th>Late Amount</th>        
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            <div style="overflow:hidden">
                                                <select class='optionId' name='OptionId[]'  required="required">
                                                </select>
                                            </div>
                                        </td>
                                        <td>
                                            <div style="overflow:hidden">
                                                <select class='OpenInternal' name='OpenInternal[]' required="required">
                                                </select>
                                            </div>
                                        </td>  
                                        <td>
                                            <div style="overflow:hidden">
                                                <input style="width:100%" type="Number" name="Quota[]" class="Quota">       
                                            </div>
                                        </td>
                                        <td>
                                            <div style="overflow:hidden">
                                                <input style="width:100%" type="Number" name="NormalAmt[]" required="required"  class="NormalAmt">       
                                            </div>
                                        </td>
                                        <td>
                                            <div style="overflow:hidden">
                                                <input style="width:100%" type="Number" name="LateAmt[]" required="required"  class="LateAmt">       
                                            </div>
                                        </td>     
                                        <td>
                                            <div style="overflow:hidden">
                                                <textarea style="width:100%" rows="3" cols="40" name="Remarks[]"  class="Remarks"></textarea>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-1">
                            <input class="deatilAddBtn btn btn-default" id="addrow" type="button" value="Add +">
                        </div>
                    </div>  
                    <?php
                    print $this->formSubmit($submit);
                    ?>                
                    <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                    <?php
                    print $this->form()->closeTag();
                    ?>
            </div>
        </div>
    </div>
</div>



