<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()
                    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
                    ->appendFile($this->basePath('js/recruitment/vacancylevel/add.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'vacancylevel');
$PositionId = $form->get('PositionId');
$PositionId->setValueOptions($Positions);
$OpeningId = $form->get('OpeningId');
$OpeningId->setValueOptions($Openings); 
$EffectiveDate = $form->get('EffectiveDate'); 
$NormalAmount = $form->get('NormalAmount');
$LateAmount = $form->get('LateAmount');
$MinAge = $form->get('MinAge');
$InclusionAmount =  $form->get('InclusionAmount');
$MaxAge = $form->get('MaxAge');
$FunctionalLevelId = $form->get('FunctionalLevelId');
$FunctionalLevelId->setValueOptions($LevelList);

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('vacancylevel', ['action' => 'add']));
$form->prepare();
?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
</script> 

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancylevel')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?> 
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cog"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
            </div>
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($OpeningId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($OpeningId); ?>
                            <?php print $this->formElementErrors()->render($OpeningId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($PositionId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($PositionId); ?>
                            <?php print $this->formElementErrors()->render($PositionId, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="FunctionalLevelId">Level</label>
                            <span class="required" aria-required="true">*</span>
                            <select name="FunctionalLevelId" id="FunctionalLevelId" required="required" tabindex="-1" aria-hidden="true">
                                
                            </select>
                        </div>
                    </div>
                    <!-- <div class="col-sm-2">
                        <div class="form-group">
                            <?php //print $this->formLabel($FunctionalLevelId); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php //print $this->formElement($FunctionalLevelId); ?>
                            <?php //print $this->formElementErrors()->render($FunctionalLevelId, ['class' => 'help-block']); ?>
                        </div>
                    </div> -->
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($EffectiveDate); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($EffectiveDate); ?>
                            <?php print $this->formElementErrors()->render($EffectiveDate, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliStartDate">&nbsp;</label>
                            <input type="text" name="nepaliStartDate" id="nepaliStartDate" class="form-control" value="">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($NormalAmount); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($NormalAmount); ?>
                            <?php print $this->formElementErrors()->render($NormalAmount, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($LateAmount); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($LateAmount); ?>
                            <?php print $this->formElementErrors()->render($LateAmount, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($InclusionAmount); ?>
                            <?php print $this->formElement($InclusionAmount); ?>
                            <?php print $this->formElementErrors()->render($InclusionAmount, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($MinAge); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($MinAge); ?>
                            <?php print $this->formElementErrors()->render($MinAge, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <?php print $this->formLabel($MaxAge); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($MaxAge); ?>
                            <?php print $this->formElementErrors()->render($MaxAge, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
                </div>
                <div class="row">
                    
                </div>
                <?php
                print $this->formSubmit($submit);
                ?>                
                <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
                <?php
                print $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>