<?php
$this->headScript()->appendFile($this->basePath('js/insurance/add-ins-dtl.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'InsuranceForm');

//$insuranceDtl = $form->get('insuranceDtl');
$employeeId = $form->get('employeeId');
$insuranceId = $form->get('insuranceId');
$premiumAmt = $form->get('premiumAmt');
$premiumDt = $form->get('premiumDt');
$remarks = $form->get('remarks');
$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');
$form->setAttribute('action', $this->url('insurance-emp-dtl', ['action' => 'addInsDtl']));
$form->prepare();
?>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i>
                    Add Employee Insurance DTL
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form); ?>
                <div class=" row">
                    <div class="col-sm-4">
                        <label>Employee Name</label>
                        <select class="form-control" name="employeeId" id="employeeId">
                            <?php  foreach($employeeList as $key => $value) {  ?>
                            <option value='<?=$key?>'><?=$value?></option>
                            <?php } ?> 
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <label>Insurance Name</label>
                        <select class="form-control" name="insuranceId" id="insuranceId">
                            <?php  foreach($insuranceList as $key => $value) {  ?>
                            <option value='<?=$key?>'><?=$value?></option>
                            <?php } ?> 
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($premiumAmt->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($premiumAmt); ?>
                            <!-- <span class="required" aria-required="true">*</span> -->
                            <?php print $this->formElement($premiumAmt); ?>
                            <?php print $this->formElementErrors()->render($premiumAmt, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <div class=" row">
                    <div class="col-sm-2">
                        <div class="form-group <?= empty($premiumDt->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($premiumDt); ?>
                            <!-- <span class="required" aria-required="true">*</span> -->
                            <?php print $this->formElement($premiumDt); ?>
                            <?php print $this->formElementErrors()->render($premiumDt, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="nepaliPremiumDt">&nbsp;</label>
                            <div class="input-group">
                                <input type="text" name="nepaliPremiumDt" id="nepaliPremiumDt" placeholder="Date in Nepali"
                                    class="form-control" value="">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group <?= empty($remarks->getMessages()) ? "" : "has-error" ?>">
                            <?php print $this->formLabel($remarks); ?>
                            <!-- <span class="required" aria-required="true">*</span> -->
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <?php print $this->formSubmit($submit); ?>
                <?php print $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>