<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/setup/training-expense/add.js'));


$amount = $form->get('amount');
$description = $form->get('description');
$trainingId = $form->get('trainingId');
$expenseHeadId = $form->get('expenseHeadId');


$submit = $form->get('submit');
$form->setAttribute('action', $this->url('trainingExpenseSetup', ['action' => 'add']));
$form->prepare();
?>

<script>
    
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.ExpenseList = <?= json_encode($expense); ?>;
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\training')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>New Entry
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>

                <div class=" row">
                  <div class="col-sm-4">
                    <label>Training Name</label>
                    <select class="form-control reset-field" name="trainingId" id="trainingId">
                            <option value='-1'>-----</option>
                            <?php foreach($training as $key => $value ){?>
                                <option value='<?=$key?>'><?=$value?></option>
                            <?php  }?>
                    </select>
                  </div>
                </div>

                <div class="row" >
                    <div class="col-md-11" >
                        <table id="expenseDetails" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th colspan="1">Expense Name</th>       
                                    <th colspan="1">Partner Name</th>             
                                    <th colspan="1">Amount</th>       
                                    <th rowspan="1">Description</th>
                                    <th rowspan="1">Action</th>        
                                </tr>
                                
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div style="overflow:hidden">
                                            <select style="width:100%" required="required" name="expenseHeadId[]" class="expenseHeadId">
                                            </select>       
                                        </div>
                                    </td>
                                    <td>
                                        <div style="overflow:hidden">
                                            <select style="width:100%" name="partnerId[]" class="partnerId">
                                            </select>       
                                        </div>
                                    </td>  
                                    <td>
                                        <div style="overflow:hidden">
                                            <input style="width:100%" type="Number" name="amount[]"   class="amount" id="amount">       
                                        </div>
                                    </td>
                                    
                                        
                                    <td>
                                        <div style="overflow:hidden">
                                            <textarea style="width:100%" rows="3" cols="40" name="description[]"  class="description"></textarea>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-1">
                        <input class="detailAddBtn btn btn-primary" type="button" value="Add +">
                    </div>
                </div>
                <!-- <input type="button" id="sumClick" value="Summation"><br><br>
                <input id="sumValue"><br><br> -->
                
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
