<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
//$this->headScript()->appendFile($this->basePath('js/setup/training/add.js'));


$amount = $form->get('amount');
$description = $form->get('description');
$trainingId = $form->get('trainingId');
$expenseHeadId = $form->get('expenseHeadId');


$submit = $form->get('submit');
$form->setAttribute('action', $this->url('trainingExpenseSetup', ['action' => 'edit','id'=>$id]));
$form->prepare();
?>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\training')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                print $this->form()->openTag($form);
                ?>
                <div class=" row">
                  <div class="col-sm-4">
                      <div class="form-group">
                          <label for="trainingId">Training Name</label>
                          <span class="required" aria-required="true">*</span>
                          <select name="trainingId" id="trainingId" required="required" class="form-control">
                              <option value=""  selected="">Please select</option>
                              <?php foreach ($training as $key => $value) {
                                  $selected = ($key == $selectedTraining) ? "selected" : ""; ?>
                                  <option <?=$selected?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
                              <?php } ?>
                          </select>
                      </div>
                  </div>
                  <div class="col-sm-4">
                      <div class="form-group">
                          <label for="expenseHeadId">Expense Name</label>
                          <span class="required" aria-required="true">*</span>
                          <select name="expenseHeadId" id="expenseHeadId" required="required" class="form-control">
                              <option value=""  selected="">Please select</option>
                              <?php foreach ($expense as $key => $value) {
                                  $selected = ($key == $selectedExpense) ? "selected" : ""; ?>
                                  <option <?=$selected?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
                              <?php } ?>
                          </select>
                      </div>
                  </div>

                </div>

                <div class=" row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($amount); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($amount); ?>

                            <?php print $this->formElementErrors()->render($amount, ['class' => 'help-block error']); ?>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group" >
                            <?php print $this->formLabel($description); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($description); ?>

                            <?php print $this->formElementErrors()->render($description, ['class' => 'help-block error']); ?>
                        </div>
                    </div>
                </div>
                <?php
                print $this->formSubmit($submit);
                print $this->form()->closeTag();
                ?>
            </div>

        </div>
    </div>
</div>
