<!DOCTYPE html>
<html>
    <head>
        <title><?php echo 'Admit_card_'.$vacancydata['FIRST_NAME'].'_'.$vacancydata['MIDDLE_NAME'].'_'.$vacancydata['LAST_NAME']; ?></title>
    </head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Mukta:wght@400;500;600&display=swap');
        body{
            font-family: 'Mukta', sans-serif;
            font-size: 14px;
        }
        
        .admit-card-wrapper{
            padding: 0 30px;
        }
        .header{
            text-align: center;
            margin: 60px 0;
        }
        .header h2{
            margin: 0;
        }
        .header h3{
            margin: 0;
        }
        .header p{
            margin: 0;
        }
        .header img{
            width: 120px;
            float: right;
        }
        .flex-box{
            display: flex;
            justify-content: space-between;
            /* padding: 0 30px; */
        }
        .applicant-info{
            width: 60%;
        }
        .table {
            width: 90%;
            margin-bottom: 8px;
        }
        .table td, .table th{
            padding: 5px;
            font-size: 13px;
        }
        .name-table {
            width: 70%;
        }
        .name-table > tbody > tr > td {
            border-top: 0;
        }
        .table>thead>tr>th, 
        .table>thead>tr>td, 
        .table>tbody>tr>th, 
        .table>tbody>tr>td, 
        .table>tfoot>tr>th, 
        .table>tfoot>tr>td {
            line-height: 1.2;
        }
        .bordered-table{
            border-spacing: 0;
        }
        .bordered-table td, .bordered-table th{
            border: 1px solid;
        }
        .document-img {
            margin-top: 50px;
            margin-right: -50px;
        }
        .document-img img{
/*            width: 300px;*/
/*            height: 200px;*/
            width: 260px;
            height: 160px;
        }
        .applicant-info p{
            margin:  30px 0 40px;
            font-size: 13px;
            line-height: 1.6;
            font-weight: 500;
        }
        /*.signature-box{
            display: flex;
            justify-content: flex-end;
        }
        .signature-box .sign1{
            margin-right: 145px;
        }*/
        .signature-box {
/*            float: left;*/
/*            text-align: right;*/
            margin-top: -100px;
        }

        .signature-box ul {
/*               text-align: right;*/
            display: flex;
            margin-left: 800px;
        }

        .signature-box ul li {
            display: inline;
        }

        .rules-wrapper {
            margin-top: 30px;
        }
        .rules-wrapper ol{
            padding-left: 10px;
        }
        .noc-stamp{
            position: absolute;
            right: 120px;
        }

        .sign1, .sign2 {
            text-align: center;
        }

        .sign1 img,
        .sign2 img {
            width: 150px;
            height: 80px;
            display: block;
            margin: 0 auto;
        }

        ul {
            padding-left: 20px;
        }

        ul li {
            list-style: none;
        }

        @media print{

            body{
                font-size: 11px;
            }
            .header {
                margin-top: 20px;
            }
            .table td, .table th{
                padding: 5px;
                font-size: 11px;
            }
            .applicant-info p {
                font-size: 11px;
                margin: 15px 0 18px;
            }
            .document-img {
                margin-top: 50px;
                margin-right: -50px;
            }
            .document-img img {
                width: 220px;
                height: 120px;
            }

            .signature-box ul {
                margin-left: 400px;
            }

            .sign1 img,
            .sign2 img {
                width: 120px;
                height: 50px;
            }

            .rules-wrapper {
                margin-top: 50px;
            }

            .document-button {
                display: none;
            }

            @page {
                margin: 0;
                page-break-after: avoid;
            }

        }
    </style>
    <body>
        <div class="document-button">
            <button class="button" onclick="printDiv('printableArea')">Download</button>
        </div>
        <div class="admit-card-wrapper" id="printableArea">
            <div class="header"> 
                <img src="<?php echo $this->basePath('img/noc.png')?>" class="noc-stamp">
                <img src="<?php echo $this->basePath('uploads/').$vacancydata['PROFILE']?>">
                <h2>नेपाल आयल निगम लिमिटेड</h1>
                <h3>केन्द्रिय कार्यालय, टेकु</h6>
                <!-- <p>लिखित अन्तर्वार्ता</p> -->
                <p>प्रवेश पत्र</p>
            </div>
            
            <div class="flex-box">
                <div class="applicant-info">
                    <table class="table name-table">
                        <tr>
                            <td>रोल नं.</td>
                            <td><?php echo $conversion['roll_no']; ?></td>
                        </tr>
                        <tr>
                            <td>नाम, थर :</td>
                            <td><?php echo base64_decode($vacancydata['NEPALI_NAME']); ?></td> 
                        </tr>
                        <tr>
                            <td>Name :</td>
                            <td><?php echo ucfirst($vacancydata['FIRST_NAME']).' '.ucfirst($vacancydata['MIDDLE_NAME']).' '.ucfirst($vacancydata['LAST_NAME']); ?></td> 
                        </tr>
                    </table>
                    <table class="table bordered-table">
                        <tr>
                            <td>विज्ञापन नं. </td>
                            <td><?php echo base64_decode($vacancydata['AD_NO_NEPALI']); ?></td>
                        </tr>
                        <tr>
                            <td>पद / तह</td>
                            <td><?php echo base64_decode($vacancydata['DESIGNATION_NTITLE']).' / '.$conversion['functional_level']; ?></td> 
                        </tr>
                        <tr>
                            <td>सेवा / समुह</td>
                            <td><?php echo base64_decode($vacancydata['SERVICE_TYPE_NAME_NEPALI']).' / '.base64_decode($vacancydata['SERVICE_EVENT_NAME_NEPALI']); ?></td> 
                        </tr>
                        <tr>
                            <td>खुला / समावेशी</td>
                            <td><?php echo $vacancydata['OPTION_NDESC'];?></td>
                        </tr>
                        <tr>
                            <td>नागरिता नं.</td>

                            <td><?php echo $conversion['citizen_no']; ?></td>
                        </tr>
                    </table>
                    <!-- <p>यस निगमबाट देहाय बमोजिमको मिति तथा केन्द्रमा लिइने उपयुक्त पदको परीक्षामा तपाईंलाई सम्मिलित हुन अनुमती दिइएको छ । विज्ञापनमा तोकिएको शर्त पुरा नभएको ठहर भएको जुनसुकै अवस्थामा पनि यो अनुमती पत्र रद्द हुनेछ । </p>p -->
                    <?php echo base64_decode($vacancyterm['DECLARATION_TEXT']); ?>
                    <table class="table bordered-table">
                        <tr>
                            <td style="width: 50px">क्र. नं.</td>
                            <!-- <td>Patra</td> -->
                            <td style="width: 60px">पत्र</td>
                            <!-- <td>Miti, Samaya, Sthan</td> -->
                            <td>मिति, समय, स्थान</td>
                        </tr>
                        <?php if ($conversion['first_venue_setup_id'] > 0) { ?>
                        <tr>
                            <td style="text-align: center;">१</td>
                            <td>प्रथम</td>
                            <td>
                                <?php
                                        echo "<strong>".$conversion['first_exam_date']."</strong>".", ".
                                             " ( ".$conversion['first_paper_time']." ) | ".
                                             "<strong>".$conversion['first_paper_venue']."</strong>";

                                ?>
                            </td> 
                        </tr>
                        <?php } ?>
                        <?php if ($conversion['second_venue_setup_id'] > 0) { ?>
                        <tr>
                            <td style="text-align: center;">२</td>
                            <td>द्वितिय</td>
                            <td>
                                <?php
                                        echo "<strong>".$conversion['second_exam_date']."</strong>".", ".
                                             " ( ".$conversion['second_paper_time']." ) | ".
                                             "<strong>".$conversion['second_paper_venue']."</strong>";

                                ?>       

                            </td> 
                        </tr>
                        <?php } ?>
                        <tr style="height: 26px;">
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr style="height: 26px;">
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
                </div>
                <div class="document-img">
                    <div class="idcard-front">
                        <img src="<?php echo $this->basePath($vacancydocument['CitizenshipF']['DOC_FOLDER']); ?>">
                    </div>
                    <div class="idcard-back" style="margin-top:10px;">
                        <img src="<?php echo $this->basePath($vacancydocument['CitizenshipB']['DOC_FOLDER']); ?>">
                    </div>
                </div>
            </div>
            <div class="signature-box">
                <ul>
                    <li class="sign1">
                        <img src="<?php echo $this->basePath($vacancydocument['Signature']['DOC_FOLDER']); ?>">
                        <!-- <span>Applicant's Sign</span> -->
                        <span>उम्मेदवार दस्तखत</span>
                    </li>
                    <li class="sign2">
                        <img src="<?php echo $this->basePath('uploads/admit/'.$vacancyterm['FILE_NAME']); ?>">
                        <!-- <span>Authorized Signature</span> -->
                        <span>आधिकारीक दस्तखत</span>
                    </li>
                </ul>
               <!--  <p class="sign1">
                    <img src="<?php echo $this->basePath($vacancydocument['Signature']['DOC_FOLDER']); ?>">
                    <span>Applicant's Sign</span>
                </p>
                <p class="sign2">
                    <img src="<?php echo $this->basePath($vacancydocument['Signature']['DOC_FOLDER']); ?>">
                    Director's Sign
                </p> -->
            </div>
            <div class="rules-wrapper">
                <p><b>उम्मेदवारले पालन गर्नुपर्ने नियमहरु :</b></p>
               <ul>
                    <li>१ परिक्षा दिन आउँदा अनिवार्य रुपमा प्रवेशपत्र ल्याउनु पर्नेछ । प्रवेशपत्र विना परिक्षमा बस्न पाइने छैन । </li>
                    <li>२. परिक्षा भवनमा मोबाइल फोन ल्याउन पाइने छैन ।</li>
                    <li>३. लिखित परिक्षाको नतिजा प्रकाशित भएपछी अन्तर्वाता हुने दिनमा पनि प्रवेशपत्र ल्याउनुपर्नेछ ।</li>
                    <li>४. परिक्षा शुरु हुने ३० मिनेट अगावै घण्टीद्वारा सुचना गरेपछी परिक्षा हलमा प्रवेश गर्न दिइने छ । बस्तुगत परिक्षा शुरु भएको १५ मिनेट पछी र बिषयगत परिक्षा शुरु भएको आधा घण्टा पछी आउने र बस्तुगत दुबै परिक्षासँग हुनेमा २० मिनेट पछी आउने उम्मेदवारले परिक्षामा बस्ने पाउने छैन ।</li>
                    <li>५. परिक्षा हलमा प्रवेश गर्न पाउने समय अवधि (बुँदा नं ४ मा उल्लेख गरिएको) बितेको १० मिनेट पछी मात्र उम्मेदवारलाई परिक्षा हल बाहिर जाने अनुमती दिइने छ ।</li>
                    <li>६. परिक्षा हलमा प्रवेश गरेपछी किताब, कापि, कागज, चिट आदि आफु साथ राख्नु हुँदैन । उम्मेदवारले आपसमा कुराकानी र संकेत गर्नु हुँदैन । </li>
                    <li>७. परिक्षा हलमा उम्मेदवारले परिक्षाको मर्यादा विपरित कुनै काम गरेमा केन्द्राध्यक्षले परिक्षा हलबाट निष्काशन गरी तुरुन्त कानुन बमोजिमको कारबाही गर्नेछ र त्यसरी निष्काशन गरिएको उम्मेदवारको सो विज्ञापनको परिक्षा  स्वत: रद्द भएको मानिने छ । </li>
                    <li>८. बिरामी भएको उम्मेदवारले परिक्षा  हलमा प्रवेश गरी परिक्षा दिने क्रममा निजलाई केही भएको निगम जवाफदेही हुने छैन ।</li>
                    <li>९. उम्मेदवारले परिक्षा दिएको दिनमा हाजिर अनिवार्य रुपमा गर्नुपर्ने छ ।</li>
                    <li>१०. निगमले सुचनाद्वारा निर्धारण  गरेको कार्यक्रम अनुसार परीक्षा सञ्चालन हुनेछ |</li>
                    <li>११. उम्मेदवारले बस्तुगत परीक्षामा आफुलाई प्राप्त प्रश्नको "KEY" उत्तरपुस्तिकामा अनिवार्य रुपले लेख्नुपर्नेछ | नलेखेमा उत्तरपुस्तिका स्वत: रद्द हुनेछ |</li>
                    <li>१२. ल्याकत (I.Q.) परीक्षामा क्यालकुलेटर प्रयोग गर्ने पाइने छैन | </li>
                    <li>१३. कुनै उम्मेदवारले प्रश्नपत्रमा रहेको अष्पष्टताको सम्बन्धमा सोध्नु पर्दा पनि परीक्षामा सम्मिलित अन्य उम्मेदवारलाई बाधा नपर्ने गरी निरिक्षकलाई सोध्नु पर्नेछ |</li>
                </ul>
                <?php #echo base64_decode($vacancyterm['TERMS']); ?>
            </div>
        </div>
    </body>

    <script type="text/javascript">
        function printDiv(divName) {
             var printContents    = document.getElementById(divName).innerHTML;
             var originalContents = document.body.innerHTML;

             window.print();
             document.body.innerHTML = printContents;

             document.body.innerHTML = originalContents;
        }
    </script>
</html>