<?php
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('js/selfservice/vacancy/index.js'));

?>

<script>
    document.viewLink = '<?= $this->url("vacancies", ["action" => "view"]) ?>';
    document.applyLink = '<?= $this->url("vacancies", ["action" => "apply"]) ?>';
    document.ids =<?php echo json_encode(["AdNo" => "", "Gender" => -1, "DepartmentId" => ""]) ?>;
    document.qualificationList = <?php echo json_encode($qualificationId); ?>;
    document.adnumberList = <?php echo json_encode($adnumber); ?>;
    document.DepartmentList = <?php echo json_encode($DepartmentId); ?>;
    document.positionList = <?php echo json_encode($positionId); ?>;
    document.openingList = <?php echo json_encode($openingId); ?>;
    
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancy')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
    </script>
<?php } ?>
<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase"> Filter</span>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group">                
                    <label for="opening">Opening No</label>
                    <!-- <input type="text" id="AdNo" name="AdNo"  class="form-control reset-field"/> -->
                    <select class="form-control" name="opening" id="openingId"></select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">                
                    <label for="AdNo">Vacancy Ad No</label>
                    <!-- <input type="text" id="AdNo" name="AdNo"  class="form-control reset-field"/> -->
                    <select multiple class="form-control" name="AdNo" id="adnumber"></select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>Qualification</label>
                    <select multiple class="form-control" name="qualification" id="qualificationId"></select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>Department</label>
                    <select multiple class="form-control" name="department" id="departmentId"></select>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <label>Position</label>
                    <select multiple class="form-control" name="position" id="positionId"></select>
                </div>
            </div>
        </div>
    </div>
            <div class="row margin-top-10">
                <div class="col-sm-offset-8 col-sm-4">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
            </div>
        </div>
</div>
    <div class="margin-top-20">
    <div id="VacancyTable">
    </div>
</div>
</div>