<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Vacancy')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
    ->appendFile($this->basePath('js/selfservice/vacancy/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'RecruitmentVacancy');
// var_dump($details); die;
$openingId = $form->get('OpeningId');
$openingId->setValueOptions($Openings);
$openingId->setAttributes(["disabled" => "disabled"]);
$QualificationId = $form->get('QualificationId');
$QualificationId->setValueOptions($QualificationList);
$QualificationId->setAttributes(["disabled" => "disabled"]);
$ServiceTypesId = $form->get('ServiceTypesId');
$ServiceTypesId->setValueOptions($ServiceTypes);
$ServiceTypesId->setAttributes(["disabled" => "disabled"]);
$ServiceEventsId = $form->get('ServiceEventsId');
$ServiceEventsId->setValueOptions($ServiceEvents);
$ServiceEventsId->setAttributes(["disabled" => "disabled"]);
$InclusionId = $form->get('InclusionId');
$InclusionId->setValueOptions($InclusionList);
$InclusionId->setAttributes(["disabled" => "disabled"]);
$SkillId = $form->get('SkillId');
$SkillId->setValueOptions($Skills);
$SkillId->setAttributes(["disabled" => "disabled"]);
$LevelId = $form->get('LevelId');
$LevelId->setValueOptions($LevelList);
$LevelId->setAttributes(["disabled" => "disabled"]);
$Vacancy_type = $form->get('Vacancy_type');
$Vacancy_type->setValueOptions($Vacancy_types);
$Vacancy_type->setAttributes(["disabled" => "disabled"]);
$Experience = $form->get('Experience');
$Experience->setAttributes(["disabled" => "disabled"]);
$Vacancy_no = $form->get('Vacancy_no');
$Vacancy_no->setAttribute('disabled', 'disabled');
$AdNo = $form->get('AdNo');
$AdNo->setAttributes(["disabled" => "disabled"]);
$VacancyReservationNo = $form->get('VacancyReservationNo');
$VacancyReservationNo->setAttributes(["disabled" => "disabled"]);
$Remark = $form->get('Remark');
$Remark->setAttributes(["disabled" => "disabled"]);
$PositionId = $form->get('PositionId');
$PositionId->setValueOptions($Positions);
$PositionId->setAttributes(["disabled" => "disabled"]);
$DepartmentId = $form->get('DepartmentId');
$DepartmentId->setValueOptions($DepartmentList);
$DepartmentId->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');

// $form->setAttribute('action', $this->url('vacancy', ['action' => 'action', 'id' => $id]));


$form->prepare();
print $this->form()->openTag($form);
?>
<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.inc = '<?php echo $inc ?>';
</script>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Vacancy Detail
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="border-bottom">
                <h2 class="d-inline bg-primary text-white text-center bold"> <img style="height:50px; padding-bottom: 4px" src="/hana-noc/neo-hris/public/img/noc-login1.png" alt="logo" class="logo-default"> Nepal Oil Corporation | Internal Vacancy</h2>
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <tr>
                                <td>Vacancy Type</td>
                                <td> <?php print $this->formElement($Vacancy_type); ?></td>
                            </tr>
                            <tr>
                                <td>Openings Number</td>
                                <td> <?php print $this->formElement($openingId); ?></td>
                            </tr> 
                            <tr>
                                <td>Advertisement Number</td>
                                <td> <?php print $this->formElement($AdNo); ?></td>
                            </tr>           
                            <tr>
                                <td>Service Types</td>
                                <td><?php print $this->formElement($ServiceTypesId); ?></td>
                            </tr>
                            <tr>
                                <td>Service group</td>
                                <td><?php print $this->formElement($ServiceEventsId); ?></td>
                            </tr>
                            <tr>
                                <td>Experience (Years)</td>
                                <td><?php print $this->formElement($Experience) ;  ?></td>
                            </tr>
                            <tr>
                                <td>Level</td>
                                <td><?php print $this->formElement($LevelId); ?></td>
                            </tr>
                            <tr>
                                <td>Qualification</td>
                                <td><?php print $this->formElement($QualificationId); ?></td>
                            </tr>
                            <tr>
                                <td>Position</td>
                                <td><?php print $this->formElement($PositionId); ?></td>
                            </tr>
                            <tr>
                                <td>Department</td>
                                <td><?php print $this->formElement($DepartmentId); ?></td>
                            </tr>
                            <tr>
                                <td>Reservation Number</td>
                                <td><?php print $this->formElement($VacancyReservationNo); ?></td>
                            </tr>
                            <tr>
                                <td>Inclusion</td>
                                <td><?php print $this->formElement($InclusionId); ?></td>
                            </tr>
                            <tr>
                                <td>Skills</td>
                                <td><?php print $this->formElement($SkillId); ?></td>
                            </tr>
                            <tr>
                                <td>Vacancy Notes:</td>
                                <td><?php print $this->formElement($Remark); ?></td>
                            </tr>
                        </tbody>
                    </table>
            </div>
            <table class="table table-striped table-bordered">
                <tbody>
                    <thead style="background-color: red; color: white;">
                        <tr>
                            <td class="text-center bold">
                                आन्तरिक प्रतियोगितात्मक परीक्षाको दरखास्त फारम 
                            </td>
                            <td class="text-center bold">
                                जेष्ठता र कार्यसम्पादन मुल्याहंन बढुवाका लागि दरखास्त फारम
                            </td>
                        </tr>
                    </thead>
                    
                    <tr> <?php //echo $this->basePath('selfservice/vacancies/perfomance/') ?>
                        <td class="text-center">
                        <?php
                        $a=0;
                        $b=0;
                        // var_dump('here');
                        if (count($vacancyApplyStage) > 0) {
                            foreach ($vacancyApplyStage as $value) {
                                if ($value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-form") {
                                   $a = 1;
                                   break;
                                } else {
                                    $a = 0;
                                }
                            }
                            foreach ($vacancyApplyStage as $value) {
                                if ($value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-performance") {
                                    $b = 1;
                                    break;
                                 } else {
                                     $b =0;
                                 }
                            }
                        }
                        if ($curentJob['FUNCTIONAL_LEVEL_NO'] < 6 ) {
                            if ($curentJob['INCLUSION'] == 'N') {
                                if ($curentJob['DURATION'] > 1) {
                                    if ($a == 1) {?>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/update/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                    <i class="fa fa-arrow-right icon-black"></i> Edit</a>
                                    <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                    <i class="fa fa-arrow-right icon-black"></i> View</a>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                   <?php } 
                                }
                            }
                            else {
                                if ($curentJob['DURATION'] > 2) { 
                                    if ($a == 1) { ?>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/update/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                    <i class="fa fa-arrow-right icon-black"></i> Edit</a>
                                    <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                    <i class="fa fa-arrow-right icon-black"></i> View</a>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                              <?php }
                               }
                               else { ?>
                                   <span>You can't apply to this Job</span> 
                            <?php   }
                            }
                        } elseif ($curentJob['FUNCTIONAL_LEVEL_NO'] > 5) {
                            if ($curentJob['INCLUSION'] == 'N') {
                                if ($curentJob['DURATION'] > 3) { 
                                        if ($a == 1) { ?>
                                            <a href="<?php echo $this->basePath('selfservice/vacancies/update/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> Edit</a>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> View</a>
                                        <?php } else { ?>
                                            <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                            <i class="fa fa-arrow-right icon-black"></i> Apzply</a>
                                    <?php   }
                                }
                            }else {
                                  if ($curentJob['DURATION'] > 4) {
                                        if ($a == 1) { ?>
                                            <a href="<?php echo $this->basePath('selfservice/vacancies/update/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> Edit</a>
                                        <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                        <i class="fa fa-arrow-right icon-black"></i> View</a>
                                        <?php } else { ?>
                                            <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                            <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                    <?php }
                                }  else { ?>
                                    you cant apply to this vacany
                            <?php    }
                            }
                        } else { ?>
                            
                      <?php  } ?>
                        
                       
                        </td>

                        <td class="text-center">
                       <?php if ($curentJob['FUNCTIONAL_LEVEL_NO'] < 6 ) {
                            if ($curentJob['INCLUSION'] == 'N') {
                                if ($curentJob['DURATION'] > 1) {
                                    if ($b == 1) { ?>
                                        <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> View</a>
                        <?php } else { ?>
                            <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                   <?php } 
                                }
                            }
                            else {
                                if ($curentJob['DURATION'] > 2) { 
                                    if ($b == 1) { ?>
                                       <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> View</a>
                        <?php } else { ?>
                            <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                              <?php }
                               }
                               else { ?>
                                   <span>You can't apply to this Job</span> 
                            <?php   }
                            }
                        } elseif ($curentJob['FUNCTIONAL_LEVEL_NO'] > 5) {
                            if ($curentJob['INCLUSION'] == 'N') {
                                if ($curentJob['DURATION'] > 3) { 
                                        if ($b == 1) { ?>
                                           <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> View</a>
                        <?php } else { ?>
                            <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                    <?php   }
                                }
                            }else {
                                  if ($curentJob['DURATION'] > 4) {
                                        if ($b == 1) { ?>
                                           <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> View</a>
                        <?php } else { ?>
                            <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                    <?php }
                                }  else { ?>
                                    you cant apply to this vacany
                            <?php    }
                            }
                        } else { ?>
                            
                      <?php  } ?>
                        <?php if ($b == 1) {?>
                            
                                <?php } ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>