<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\Vacancy')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'))
    ->appendFile($this->basePath('js/selfservice/vacancy/view.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'RecruitmentVacancy');
// var_dump($details); die;
$openingId = $form->get('OpeningId');
$openingId->setValueOptions($Openings);
$openingId->setAttributes(["disabled" => "disabled"]);

$QualificationId = $form->get('QualificationId');
$QualificationId->setValueOptions($QualificationList);
$QualificationId->setAttributes(["disabled" => "disabled"]);

$ServiceTypesId = $form->get('ServiceTypesId');
$ServiceTypesId->setValueOptions($ServiceTypes);
$ServiceTypesId->setAttributes(["disabled" => "disabled"]);
$ServiceEventsId = $form->get('ServiceEventsId');
$ServiceEventsId->setValueOptions($ServiceEvents);
$ServiceEventsId->setAttributes(["disabled" => "disabled"]);

$InclusionId = $form->get('InclusionId');
$InclusionId->setValueOptions($InclusionList);
$InclusionId->setAttributes(["disabled" => "disabled"]);

$SkillId = $form->get('SkillId');
$SkillId->setValueOptions($Skills);
$SkillId->setAttributes(["disabled" => "disabled"]);

$LevelId = $form->get('LevelId');
$LevelId->setValueOptions($LevelList);
$LevelId->setAttributes(["disabled" => "disabled"]);

$Vacancy_type = $form->get('Vacancy_type');
$Vacancy_type->setValueOptions($Vacancy_types);
$Vacancy_type->setAttributes(["disabled" => "disabled"]);

$Experience = $form->get('Experience');
$Experience->setAttributes(["disabled" => "disabled"]);

$Vacancy_no = $form->get('Vacancy_no');
$Vacancy_no->setAttribute('disabled', 'disabled');

$AdNo = $form->get('AdNo');
$AdNo->setAttributes(["disabled" => "disabled"]);

$VacancyReservationNo = $form->get('VacancyReservationNo');
$VacancyReservationNo->setAttributes(["disabled" => "disabled"]);

$Remark = $form->get('Remark');
$Remark->setAttributes(["disabled" => "disabled"]);

$PositionId = $form->get('PositionId');
$PositionId->setValueOptions($Positions);
$PositionId->setAttributes(["disabled" => "disabled"]);

$DepartmentId = $form->get('DepartmentId');
$DepartmentId->setValueOptions($DepartmentList);
$DepartmentId->setAttributes(["disabled" => "disabled"]);

$submit = $form->get('submit');

// $form->setAttribute('action', $this->url('vacancy', ['action' => 'action', 'id' => $id]));


$form->prepare();
    print $this->form()->openTag($form);
    print $this->form()->closeTag($form);

?>

<script>
    document.urlCss = '<?= $this->basePath('css/custom.css') ?>';
    document.inc    = '<?php echo $inc ?>';
</script>


<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Vacancy Detail
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="border-bottom">
                <h2 class="d-inline bg-primary text-white text-center bold">
                    <img style="height:50px; padding-bottom: 4px" src="/img/noc-login1.png" alt="logo" class="logo-default"> Nepal Oil Corporation | Internal Vacancy
                </h2>

                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <td>Vacancy Type</td>
                            <td> <?php print $this->formElement($Vacancy_type); ?></td>
                        </tr>
                        <tr>
                            <td>Openings Number</td>
                            <td> <?php print $this->formElement($openingId); ?></td>
                        </tr> 
                        <tr>
                            <td>Advertisement Number</td>
                            <td> <?php print $this->formElement($AdNo); ?></td>
                        </tr>           
                        <tr>
                            <td>Service Types</td>
                            <td><?php print $this->formElement($ServiceTypesId); ?></td>
                        </tr>
                        <tr>
                            <td>Service group</td>
                            <td><?php print $this->formElement($ServiceEventsId); ?></td>
                        </tr>
                        <tr>
                            <td>Experience (Years)</td>
                            <td>
                                <?php if (isset($detail['MENTIONED_EXPERIENCE'])) { ?>
                                <input name="Experience" id="Experience" class="Experience form-control" disabled="disabled" type="text" value="<?php echo $detail['MENTIONED_EXPERIENCE'];?>">
                                <?php } else { ?> 
                                <?php print $this->formElement($Experience) ;  ?>
                                <?php } ?>
                            </td>
                        </tr>
                        <?php 
                            /**
                             * IS_INCLUSION_USED_PROCESS 
                             * 
                             * AP = APPROVED   [MEANS INCLUSION ALREADY USED IN PAST APPLICATION]
                             * 
                             * INCLUSION CAN USED FOR BOTH INTERNAL-FORM AND INTERNAL-APPRAISAL
                             * 
                             * INCLUSION CAN APPLY IN BOTH 
                             * 
                             * EITHER SELECTED ON FORM OR APPRAISAL THEN DISABLE USE OF INCLUSION IN FUTURE APPLICATION
                             * 
                             * 
                             * 
                             * */
                            if ($employeeInclusionUsedForm['INCLUSION_USED_PROCESS'] !== 'AP') { ?>
                           
                        <tr>
                            <td>
                                Inclusion Eligible ?
                            </td>

                            <?php 
                                /**
                                 * CHECKING FOR END DATE
                                 * */

                                if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                        
                             ?>
                            <td>
                                <form method="post" enctype="multipart/form-data" action="">

                                    <?php #echo "<pre>"; print_r($employeeDetail); die;?>
                                    
                                    <div class="form-group">
                                        <!-- <h4>Inclusion Eligible ?</h4> -->
                                        <label>Yes Eligible Inclusion</label>
                                        <input 
                                            type="checkbox" 
                                            name="has_inclusion" 
                                            value="Y" 
                                            class="is_inclusion_check" 
                                            onclick="valueChanged()" 
                                            <?php 
                                                /**
                                                 * EITHER CHECKING ELIGIBLE INCLUSION FROM FORM OR APPRAISAL
                                                 * 
                                                 * */
                                                if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                    echo ($employeeInclusionUsedAppraisal['INCLUSION_APPRAISAL_USED'] == 'Y') ? 'checked' : ''; 

                                                } else {

                                                    echo ($employeeInclusionUsedForm['INCLUSION_FORM_USED'] == 'Y') ? 'checked' : ''; 

                                                }

                                            ?>
                                        >
                                    </div>

                                    <?php  
                                        /**
                                         * DISPLAY OR NOT INCLUSION SELECTION CONTENT AS INCLUSION HAVE
                                         * 
                                         * */
                                        if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                            $display = ($employeeInclusionUsedAppraisal['INCLUSION_APPRAISAL_USED'] == 'Y') ? 'block' : 'none'; 

                                        } else {

                                            $display = ($employeeInclusionUsedForm['INCLUSION_FORM_USED'] == 'Y') ? 'block' : 'none'; 

                                        }

                                     ?>

                                    <div class="inclusion-content"  style="display: <?php echo (isset($display)) ? $display : ''; ?>;">
                                        <div class="alert alert-info">
                                            Employee can update their experience. Please upload inclusion photo (*required if using inclusion)
                                        </div>

                                        <div class="inclusion-list">
                                            <?php foreach ($inclusionLists as $inclusion) { ?>

                                                <div class="form-check form-check-inline">
                                                    <input 
                                                        class="form-check-input inclusion_upload" 
                                                        id="inclusion<?php echo $inclusion['OPTION_ID'];?>" 
                                                        type="radio" 
                                                        value="<?php echo $inclusion['OPTION_ID']; ?>" 
                                                        name="inclusion_id" 
                                                        uploadFlag="<?php echo $inclusion['UPLOAD_FLAG'];?>" 
                                                        required 
                                                        <?php 
                                                            /**
                                                             * FOR SHOW SELECTED INCLUSION
                                                             * 
                                                             * */
                                                            if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                                echo ($employeeInclusionUsedAppraisal['INCLUSION_ID_APPRAISAL'] == $inclusion['OPTION_ID']) ? 'checked' : ''; 

                                                            } else {

                                                                echo ($employeeInclusionUsedForm['INCLUSION_ID_FORM'] == $inclusion['OPTION_ID']) ? 'checked' : ''; 

                                                            }
                                                            
                                                        ?>

                                                        <?php 
                                                            /**
                                                             * IF INCLUSION ALREADY USED THEN DISABLE ON SELECTION
                                                             * */

                                                            if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                                echo ($employeeInclusionUsedAppraisal['INCLUSION_APPRAISAL_USED'] == 'Y') ? 'disabled' : ''; 

                                                            } else {

                                                                echo ($employeeInclusionUsedForm['INCLUSION_FORM_USED'] == 'Y') ? 'disabled' : ''; 

                                                            }
                                                            
                                                        ?> 

                                                       >

                                                    <label class="form-check-label" for="inlineCheckbox1">
                                                        <?php echo ucwords($inclusion['OPTION_EDESC']); ?>
                                                    </label>
                                                </div>


                                            <?php } ?>
                                        </div>

                                        <input type="hidden" name="has_vacancy_id" value="<?php echo $detail['VACANCY_ID'];?>">
                                        <input type="hidden" name="has_employee_id" value="<?php echo $employeeDetail['EMPLOYEE_ID'];?>">
                                        <input type="hidden" name="form_type" value="<?php echo $detail['VACANCY_TYPE']; ?>">
                                        <input type="hidden" name="vacancy_opening_date" value="<?php echo $openingAdInfo['START_DATE']; ?>">

                                        <div class="form-group inclusion_upload_file" style="display: none;">
                                            <label>Upload Inclusion</label>
                                            <input type="file" name="has_inclusion_file" class="form-control has_inclusion_file" id="inclusion_image">
                                            
                                        </div>

                                        <?php 
                                        
                                            if (($employeeInclusionUsedAppraisal['INCLUSION_APPRAISAL_FILE_ID'] > 0) || 
                                                ($employeeInclusionUsedForm['INCLUSION_FORM_FILE_ID'] > 0)) { 
                                        
                                        ?>
                                        <div class="form-group">
                                            <div class="inclusion_file_display">
                                                <?php 
                                                    
                                                    if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                        if ($employeeInclusionUsedAppraisal['FILE_PATH'] !== '') {

                                                ?>
                                                <img 
                                                    src="<?php echo $baseurl;?>/uploads/documents/Inclusion/<?php echo $employeeInclusionUsedAppraisal['FILE_PATH'];?>" 
                                                    alt="inclusion-image" 
                                                    style="width:20%">
                                                
                                                <?php } 

                                                    }  else { 

                                                        if ($employeeInclusionUsedForm['FILE_PATH'] !== '') {
                                                ?>

                                                <img 
                                                    src="<?php echo $baseurl;?>/uploads/documents/Inclusion/<?php echo $employeeInclusionUsedForm['FILE_PATH'];?>" 
                                                    alt="inclusion-image" 
                                                    style="width:20%">

                                                <?php } } } ?>

                                            </div>
                                        </div>

                                        <?php 
                                            /**
                                             * VIEW OR DOWNLOAD INCLUSION
                                             * */

                                            if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                if ($employeeInclusionUsedAppraisal['FILE_PATH']) {
                                        ?>
                                                <div class="form-group">
                                                    <a href="<?php echo $baseurl;?>/uploads/documents/inclusion/<?php echo $employeeInclusionUsedAppraisal['FILE_PATH'];?>" class="btn btn-primary" target="_blank">View</a>
                                                    <a href="<?php echo $baseurl;?>/uploads/documents/inclusion/<?php echo $employeeInclusionUsedAppraisal['FILE_PATH'];?>" class="btn btn-success" download>Download</a>
                                                </div>

                                        <?php } 

                                                } else { 

                                                    if ($employeeInclusionUsedForm['FILE_PATH']) {

                                        ?>

                                                <div class="form-group">
                                                    <a href="<?php echo $baseurl;?>/uploads/documents/inclusion/<?php echo $employeeInclusionUsedForm['FILE_PATH'];?>" class="btn btn-primary" target="_blank">View</a>
                                                    <a href="<?php echo $baseurl;?>/uploads/documents/inclusion/<?php echo $employeeInclusionUsedForm['FILE_PATH'];?>" class="btn btn-success" download>Download</a>
                                                </div>

                                        <?php } } ?>



                                        <p id="error1" style="display:none; color:#FF0000;">
                                            Invalid Image Format! Image Format Must Be JPG, JPEG, PNG or GIF.
                                        </p>
                                        <p id="error2" style="display:none; color:#FF0000;">
                                            Maximum File Size Limit is 1MB.
                                        </p>
                                        
                                        <?php 
                                            if ($detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL') {

                                                if ($employeeInclusionUsedAppraisal['INCLUSION_APPRAISAL_USED'] !== 'Y') {

                                        ?>
                                             <button type="submit" class="btn btn-success" value="update_inclusion" name="update_inclusion" id="update_inclusion">Update Inclusion</button>
                                        
                                        <?php 
                                                } 

                                            } else { 

                                                if ($employeeInclusionUsedForm['INCLUSION_FORM_USED'] !== 'Y') {
                                        ?>
                                            
                                            <button type="submit" class="btn btn-success" value="update_inclusion" name="update_inclusion" id="update_inclusion">Update Inclusion</button>

                                        <?php } } ?>




                                    </div>
                                </form>
                            </td>
                            <?php } ?>
                        </tr>

                        <?php } ?>

                        <tr>
                            <td>Level</td>
                            <td><?php print $this->formElement($LevelId); ?></td>
                        </tr>
                        <tr>
                            <td>Qualification</td>
                            <td><?php print $this->formElement($QualificationId); ?></td>
                        </tr>
                        <tr>
                            <td>Position</td>
                            <td><?php print $this->formElement($PositionId); ?></td>
                        </tr>
                        <tr>
                            <td>Department</td>
                            <td><?php print $this->formElement($DepartmentId); ?></td>
                        </tr>
                        <tr>
                            <td>Reservation Number</td>
                            <td><?php print $this->formElement($VacancyReservationNo); ?></td>
                        </tr>
                        <tr>
                            <td>Inclusion</td>
                            <td><?php print $this->formElement($InclusionId); ?></td>
                        </tr>
                        <tr>
                            <td>Skills</td>
                            <td><?php print $this->formElement($SkillId); ?></td>
                        </tr>
                        <tr>
                            <td>Vacancy Notes:</td>
                            <td><?php print $this->formElement($Remark); ?></td>
                        </tr>
                    </tbody>
                </table>

            </div>

            <table class="table table-striped table-bordered">
                <tbody>
                    <thead style="background-color: red; color: white;">
                        <tr>
                            <?php if( $detail['VACANCY_TYPE'] == 'INTERNAL_FORM' ) { ?>

                            <td class="text-center bold"> आन्तरिक प्रतियोगितात्मक परीक्षाको दरखास्त फारम </td>

                            <?php } elseif ( $detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL' ) { ?>

                            <td class="text-center bold"> जेष्ठता र कार्यसम्पादन मुल्याहंन बढुवाका लागि दरखास्त फारम </td>
                            
                            <?php } ?>
                        </tr>
                    </thead>

                    <tr> 
                        <?php //echo $this->basePath('selfservice/vacancies/perfomance/') ?>
                        <?php 
                            /* VACANCY TYPE INTERNAL FORM*/

                            if ( $detail['VACANCY_TYPE'] == 'INTERNAL_FORM' ) {

                        ?>

                        <td class="text-center">
                            <?php if ($applicationApplied['IS_ADMIT_GENERATED'] == 'Y') { ?>
                            <a class="btn btn-success" id="downloadAdminCard1" href="<?php echo $this->basePath().'/selfservice/vacancies/admitcard/'.$applicationApplied['APPLICATION_ID']; ?>" target="_blank">Admit Card</a>
                            <?php } ?>
                            <?php
                                $a = 0; $b = 0;
                                
                                $a_admin_generated = 0;
                                $b_admin_generated = 0;
                            
                                
                                if ( count($vacancyApplyStage) > 0 ) {

                                    foreach ( $vacancyApplyStage as $value ) {

                                        if ( $value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-form") {
                                            
                                            $a = 1;

                                            /* FOR ADMIN CARD*/
                                            if ( $value['ADMIN_CARD_GENERATED'] == 'Y') {
                                                    $a_admin_generated = 1;
                                            }

                                            break;

                                        } else {

                                            $a = 0;

                                        }
                                    }

                                    foreach ($vacancyApplyStage as $value) {

                                        if ($value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-performance") {

                                            $b = 1;

                                            /* FOR ADMIN CARD*/
                                            if ( $value['ADMIN_CARD_GENERATED'] == 'Y' ) {
                                                $b_admin_generated = 1;
                                            }

                                            break;

                                        } else {
                                            
                                            $b = 0;
                                        
                                        }
                                    }
                                }

                                /**
                                 *  CHECKING USER FUNCTIONAL LEVEL
                                 *  
                                 * */
                                if ( $curentJob['FUNCTIONAL_LEVEL_NO'] < 6 ) {

                                    if ($curentJob['INCLUSION'] == 'N') {

                                        // if ($curentJob['DURATION'] > 1) {
                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                            if ( $a == 1 ) { ?>

                                                <?php 
                                                    /**
                                                     * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                     * */
                                                    if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-form') { 

                                                        if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                ?>

                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/editApplicationForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Edit
                                                    </a>
                                                <?php 

                                                        }

                                                    }

                                                ?>


                                                <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> View
                                                </a>

                                            <?php } else { ?>

                                                 <?php 
                                                    /**
                                                     * CHECKING FOR END DATE
                                                     * */

                                                    if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                            
                                                 ?>
                                                

                                                <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                                <?php } ?>

                                            <?php } 

                                        } else {
                                                
                                            echo "<span>you can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] . " years</span>" ;
                                        }
                                   
                                    } else {

                                        // if ($curentJob['DURATION'] > 2) { 
                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                            if ( $a == 1 ) { ?>

                                                <?php 
                                                    /**
                                                     * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                     * */
                                                    if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-form') { 

                                                        if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                ?>
                                                <a href="<?php echo $this->basePath('selfservice/vacancies/editApplicationForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Edit
                                                </a>
                                                <?php 
                                                        }
                                                    }
                                                ?>
                                                <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> View
                                                </a>
                                                
                                            <?php } else { ?>

                                                <?php 
                                                    /**
                                                     * CHECKING FOR END DATE
                                                     * */

                                                    if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                            
                                                 ?>
                                                <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                                <?php } ?>
                                            
                                            <?php }
                                            
                                        } else { 
                                            
                                            echo "<span>you can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years</span>";

                                        }

                                    }

                                } elseif ( $curentJob['FUNCTIONAL_LEVEL_NO'] > 5 ) {

                                    if ( $curentJob['INCLUSION'] == 'N' ) {

                                        // if ($curentJob['DURATION'] > 3) { 
                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                                if ($a == 1) { ?>

                                                    <?php 
                                                        /**
                                                         * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                         * */
                                                        if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-form') { 

                                                            if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                    ?>
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/editApplicationForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Edit
                                                    </a>
                                                    <?php 
                                                            }
                                                        }
                                                    ?>
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> View
                                                    </a>

                                                    <?php if ( $a_admin_generated == 1 ) { ?>
                                                        <a class="btn btn-success" id="downloadAdminCard">Download Admin Card</a>
                                                        <!-- <i class="fa fa-arrow-right icon-black"></i> View Admin Card</a> -->
                                                    <?php } else { ?>
                                                        <h5>Your admin card will shortly be generated after payment.</h5>
                                                    <?php }

                                                } else { ?>
                                                         <?php 
                                                            /**
                                                             * CHECKING FOR END DATE
                                                             * */

                                                            if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                                    
                                                         ?>
                                                        <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                                        <?php } ?>
                                        <?php   }

                                        } else {

                                           echo "<span>you can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years</span>";

                                        }

                                    } else {

                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                            // if ($curentJob['DURATION'] > 4) {
                                                if ($a == 1) { ?>
                                                     <?php 
                                                        /**
                                                         * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                         * */
                                                        if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-form') { 

                                                            if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                    ?>
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/editApplicationForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Edit
                                                    </a>
                                                    <?php 
                                                            }
                                                        }
                                                    ?>
                                                    <!-- <a style="display:none;" href="<?php #echo $this->basePath('selfservice/vacancies/update/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Edit
                                                    </a> -->
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/view-application-form/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> View
                                                    </a>

                                            <?php } else { ?>

                                                    <?php 
                                                        /**
                                                         * CHECKING FOR END DATE
                                                         * */

                                                        if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                                
                                                    ?>
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/apply/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Apply</a>
                                                    <?php } ?>

                                            <?php }

                                        }  else { 
                                            
                                            echo "<span>You can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years</span>";
                                        }
                                    }

                                } else {
                                    
                                } 
                            ?>
                        
                       
                        </td>
                        <?php 
                            /* VACANCY TYPE INTERNAL APPRAISAL */

                            } elseif ( $detail['VACANCY_TYPE'] == 'INTERNAL_APPRAISAL' ) {




                        ?>

                        <td class="text-center">

                            <?php

                                $a=0; $b=0;

                                $a_admin_generated = 0;
                                $b_admin_generated = 0;
                                
                                // var_dump('here');
                                if ( count($vacancyApplyStage) > 0 ) {

                                    foreach ( $vacancyApplyStage as $value ) {

                                        if ( $value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-form" ) {
                                        
                                            $a = 1;


                                            if ( $value['ADMIN_CARD_GENERATED'] == 'Y' ) {
                                                    $a_admin_generated = 1;
                                            }

                                            break;

                                        } else {

                                            $a = 0;

                                        }

                                    }

                                    foreach ( $vacancyApplyStage as $value ) { 

                                        echo "<h1>". $value['APPLICATION_TYPE']."</h1>";

                                        if ( $value['USER_ID'] == $user_id && $value['APPLICATION_TYPE'] == "Internal-performance" ) {

                                            $b = 1;

                                            if ( $value['ADMIN_CARD_GENERATED'] == 'Y' ) {

                                                $b_admin_generated = 1;

                                            }

                                            break;

                                        } else {

                                            $b = 0;

                                        }

                                    }
                                }

                                if ( $curentJob['FUNCTIONAL_LEVEL_NO'] < 6 ) {

                                    if ( $curentJob['INCLUSION'] == 'N' ) {

                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                            // if ($curentJob['DURATION'] > 1) {
                                            if ($b == 1) { ?>

                                                <?php 
                                                    /**
                                                     * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                     * */
                                                    if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-performance') { 

                                                        if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                ?>
                                                <a href="<?php echo $this->basePath('selfservice/vacancies/editPerformanceForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Edit
                                                </a>
                                                <?php 
                                                        }
                                                    }
                                                ?>
                                                

                                                <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> View
                                                </a>

                                        <?php } else { ?>

                                                <?php 
                                                    /**
                                                     * CHECKING FOR END DATE
                                                     * */

                                                    if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                            
                                                 ?>

                                                <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Apply
                                                </a>

                                                <?php } ?>

                                        <?php } 

                                        } else {
                                            
                                            echo "<span> You can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years </span>";
                                        }
                                        
                                    } else {

                                        if ($curentJob['DURATION'] >= $detail['EXPERIENCE']) {

                                            // if ($curentJob['DURATION'] > 2) { 
                                            if ($b == 1) { ?>

                                                <?php 
                                                    /**
                                                     * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                     * */
                                                    if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-performance') { 

                                                        if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                ?>
                                                <a href="<?php echo $this->basePath('selfservice/vacancies/editPerformanceForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Edit
                                                </a>
                                                <?php 
                                                        }
                                                    }
                                                ?>

                                                <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> View 
                                                </a>
                                        <?php } else { ?>

                                                 <?php 
                                                    /**
                                                     * CHECKING FOR END DATE
                                                     * */

                                                    if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                            
                                                 ?>
                                                <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                    <i class="fa fa-arrow-right icon-black"></i> Apply
                                                </a>
                                                <?php } ?>
                                        <?php }

                                        } else { 
                                            
                                            echo "<span>you can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years</span>"; 
                                        }

                                    }

                                } elseif ( $curentJob['FUNCTIONAL_LEVEL_NO'] > 5 ) {

                                    if ($curentJob['INCLUSION'] == 'N') {

                                        if ($curentJob['DURATION'] > $detail['EXPERIENCE']) {
                                            // if ($curentJob['DURATION'] > 3) { 
                                                if ($b == 1) { ?>

                                                    <?php 
                                                        /**
                                                         * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                         * */
                                                        if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-performance') { 

                                                            if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                                    ?>
                                                    <a href="<?php echo $this->basePath('selfservice/vacancies/editPerformanceForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Edit
                                                    </a>
                                                    <?php 
                                                            }
                                                        }
                                                    ?>

                                                    <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> View
                                                    </a>

                                            <?php } else { ?>

                                                <?php 
                                                    /**
                                                     * CHECKING FOR END DATE
                                                     * */

                                                    if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                            
                                                ?>
                                                    <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                        <i class="fa fa-arrow-right icon-black"></i> Apply
                                                    </a>
                                                <?php } ?>
                                            <?php }
                                                
                                        } else { 
                                            
                                            echo "<span> You can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years </span>";
                                        }
                                            
                                    } else {

                                        if ( $curentJob['DURATION'] > $detail['EXPERIENCE'] ) {

                                            // if ($curentJob['DURATION'] > 4) {
                                            if ($b == 1) { ?>

                                            <?php 
                                                /**
                                                 * CHECK STAGE AND HAVE EDIT AVAILABLE
                                                 * */
                                                if ($applicationApplied['APPLICATION_TYPE'] == 'Internal-performance') { 

                                                    if ($getApplicationStage['ALLOW_EDIT'] == 'Y') {
                                            ?>
                                            <a href="<?php echo $this->basePath('selfservice/vacancies/editPerformanceForm/') . $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                <i class="fa fa-arrow-right icon-black"></i> Edit
                                            </a>
                                            <?php 
                                                    }
                                                }
                                            ?>

                                            <a href="<?php echo  $this->basePath('selfservice/vacancies/view-performance-form/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                <i class="fa fa-arrow-right icon-black"></i> View
                                            </a>

                                     <?php } else { ?>

                                             <?php 
                                                /**
                                                 * CHECKING FOR END DATE
                                                 * */

                                                if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {
                                                                        
                                             ?>
                                            <a href="<?php echo  $this->basePath('selfservice/vacancies/perfomance/'). $detail['VACANCY_ID'] ?>" class="btn default btn-sm green">
                                                <i class="fa fa-arrow-right icon-black"></i> Apply
                                            </a>
                                            <?php } ?>
                                      <?php }
                                                
                                    }  else {

                                        echo "<span> You can not apply to this vacany because your job duration is less than ". $detail['EXPERIENCE'] ." years </span>";
                                    
                                    }
                                            
                                }
                                        
                            } else { 
                                            
                            } ?>
                                    
                            <?php if ($b == 1) {} ?>
                        </td>

                        <?php } ?>


                        

                    </tr>
                </tbody>
            </table>
            <?php  #echo "<pre>"; print_r($getApplicationStage); die; ?>

                <?php if ( $applicationApplied ) {
                        if ( $applicationApplied['PAYMENT_PAID'] !== 'Y') { 

                            if (strtotime($openingAdInfo['END_DATE']) >= strtotime(date('Y-m-d'))) {

                ?> 
                    <a class="btn default btn-sm blue" data-toggle="modal" data-target="#paymentModal">Payment</a>

                    <div class="modal fade" id="paymentModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="paymentModal" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Choose Payment</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <ul class="list-inline" style="display: flex;">
                                        <?php  
                                            foreach ($paymentGateways as $paymentGateway) { 
                                                /**
                                                 *  vid : VACANCY ID
                                                 *  aid : APPLICATION ID
                                                 *  pid : PAYMENT GATEWAY ID
                                                 *  uid : USER ID
                                                 * 
                                                 * */
                                                $param = 'vid'.$applicationApplied['AD_NO'].'&'.'aid'.$applicationApplied['APPLICATION_ID'].'&'.'pid'.$paymentGateway['ID'].'&'.'uid'.$applicationApplied['USER_ID'];

                                        ?>
                                        <li>
                                            <a 
                                            <?php 

                                                echo ($paymentGateway['GATEWAY_COMPANY'] !== 'connectips') ? 
                                                "href='".$this->basePath()."selfservice/vacancies/payments/".$param."'" : ''; 

                                            ?>>
                                                <img src="<?php echo $this->basePath('img/'.$paymentGateway['GATEWAY_LOGO']) ?>" alt="<?php echo $paymentGateway['GATEWAY_COMPANY'] ?>" style="width: 40%;" 
                                                <?php echo ($paymentGateway['GATEWAY_COMPANY'] == 'connectips') ? 
                                                    "onclick='return handle_connectips()'" : ''; ?>>
                                            </a>
                                        </li>
                                        <?php } ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- CONNECTIPS FORM -->
                    <form action="https://login.connectips.com/connectipswebgw/loginpage" id="IPSSubmit" method="POST" url="<?php echo $baseurl;  ?>">

                        <input type="hidden" name="MERCHANTID" id="MERCHANTID" value="<?php echo $connectIpsData['merchant_id']; ?>"/>
                        <input type="hidden" name="APPID" id="APPID" value="<?php echo $connectIpsData['app_id']; ?>"/>
                        <input type="hidden" name="APPNAME" id="APPNAME" value="<?php echo $connectIpsData['app_name']; ?>"/>
                        <input type="hidden" name="TXNID" id="TXNID" value="<?php echo $connectIpsData['txn_id']; ?>"/> 
                        <input type="hidden" name="TXNDATE" id="TXNDATE" value="<?php echo $connectIpsData['txn_date']; ?>"/>
                        <input type="hidden" name="TXNCRNCY" id="TXNCRNCY" value="<?php echo $connectIpsData['txn_currency']; ?>"/>
                        <input type="hidden" name="TXNAMT" id="TXNAMT" value="<?php echo $connectIpsData['txn_amount']; ?>"/>
                        <input type="hidden" name="REFERENCEID" id="REFERENCEID" value="<?php echo $connectIpsData['reference_id']; ?>"/>
                        <input type="hidden" name="REMARKS" id="REMARKS" value="<?php echo $connectIpsData['remarks']; ?>"/>
                        <input type="hidden" name="PARTICULARS" id="PARTICULARS" value="<?php echo $connectIpsData['particulars']; ?>"/>
                        <input type="hidden" name="TOKEN" id="TOKEN" value="<?php echo $connectIpsData['token']; ?>"/>

                    </form>

                <?php } else { ?>
                    <h3 class="text-center btn btn-primary">Unpaid</h3>
                <?php } } else { ?>

                    <h3 class="text-center btn btn-primary">Payment Paid</h3>
                <?php } } ?>
        </div>
    </div>
</div>

<div id="adminCard" class="col-md-8"  style="border:1px solid; display: none;">
<?php print $this->partial('partials/admin-card.phtml'); ?>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>

    function handle_connectips() {

        $('#IPSSubmit').submit();

    }

    function valueChanged() {

        if($('.is_inclusion_check').is(":checked")) {

            $(".inclusion-content").show();
        
        } else {
        
            $(".inclusion-content").hide();
        
        }

    }

    $('.inclusion_upload').on('click', function() {

        inclusion_id = $(this).attr('id');
    
        inclusion_attr = $('#'+inclusion_id).attr('uploadFlag');


        if (inclusion_attr == 'Y') {

            $(".inclusion_upload_file").show();
            $(".has_inclusion_file").attr("required", true);


        } else {


            $(".inclusion_upload_file").hide();
            $(".has_inclusion_file").removeAttr('required');

        }

    });

    var a = 0;
    //binds to onchange event of your input field
    $('#inclusion_image').bind('change', function() {

        var ext = $('#inclusion_image').val().split('.').pop().toLowerCase();

        if ($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {

            $('#error1').slideDown("slow");
            $('#error2').slideUp("slow");

            $('#update_inclusion').css('display', 'none');

            a = 0;
       
        } else {

            $('#error1').slideUp("slow");

            $('#update_inclusion').css('display', 'block');


        }
        

    });

</script>