<?php
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));
$this->headLink()->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('js/selfservice/vacancy/apply.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'perfomanceApplication-form');

// $fromDate = $form->get('fromDate');
// $toDate = $form->get('toDate');
// $duration = $form->get('duration');
// $remarks = $form->get('remarks');

$submit = $form->get('submit');
$submit->setAttribute('value', 'Apply');
?>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\vacancies')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Vacancy Apply
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>" />
            </div>
            <?php print $this->form()->openTag($form);  ?>
            <h4 class="text-center"> <strong style="line-height: 25px;"> नेपाल आइल निगम लिमिटेड <br> कर्मचारी प्रशासन विनियमावली २०६३ को विनियम ६,४ बमोजिम  <br>जेष्ठता र कार्यसम्पादन मुल्याहंन बढुवाका लागि  <br> दरखास्त फारम </strong></h4>
            <div class="row" style="margin: 20px;">
                <h5 class="bold">कर्मचारी संकेत न: <?=$EmployeeData['EMPLOYEE_CODE']?></h5>
                <div class="col-12" style="border:1px solid black ;">
                    <div class="row clearfix e-setup">                    
                        <div class="col-xs-12 col-sm-3 col-md-6 col-box">
                            <div class="row bottomgap">
                                <div class="form-group" style="margin: 10px;">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="ad_no">सूचना न.:  </label><?php // / प्रकाशन भएको मिति ?>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $detail['AD_NO'] ?></div> <?php //. ' / 2021-1-1' ?>
                                </div>
                            </div>
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="firstName">बढुवा हुने पद / तह :</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $detail['POSITION_NAME'].' / '. $detail['FUNCTIONAL_LEVEL_NO'];?></div>
                                </div>
                            </div>                            
                        </div>
                        <div class="col-xs-12 col-sm-3 col-md-6 col-box">
                            <div class="row bottomgap">
                                <div class="form-group" style="margin: 10px;">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="ad_no">सेवा / समुह:  </label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                    <?php echo $detail['SERVICE_EVENT_NAME'].'/ '. $detail['SERVICE_TYPE_NAME'];?></div>
                                </div>
                            </div>

                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="firstName">बि. न. :</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $detail['AD_NO'] ?></div>
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
                <div class="col-12" style="border:1px solid black; margin-top: 10px">
                    <div class="row clearfix e-setup">                    
                        <div class="col-xs-12 col-sm-3 col-md-6 col-box">
                            <div class="row bottomgap">
                                <div class="form-group" style="margin: 10px;">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="ad_no">उमेद्वारको नाम / थर:  </label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $EmployeeData['FIRST_NAME'] .' '.$EmployeeData['MIDDLE_NAME'].' ' .$EmployeeData['LAST_NAME'] ?></div>
                                </div>
                            </div>
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="firstName">बहाल रहेको कार्यालय:</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $EmployeeData['DEPARTMENT_ID'] ?></div>
                                </div>
                            </div>
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="firstName">पद / तह:</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $EmployeeData['DESIGNATION_TITLE'].' / '. $EmployeeData['POSITION_ID'] ?></div>
                                </div>
                            </div>  
                            <div class="row bottomgap">
                                <div class="form-group">
                                    <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                        <label for="firstName">सेवा / समुह:</label>
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                        <?php echo $EmployeeData['SERVICE_TYPE_NAME'].' / '. $EmployeeData['SERVICE_EVENT_NAME'] ?></div>
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
                    <h5 class="bold">१. सेवा सम्बन्धी बिवरण ( शुरू नियुक्तिदेखि हालको पदसम्म )</h5>
                <div class="row">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td class="text-center"  style="width: 10%;">पद</td>
                                <td class="text-center"  style="width: 20%;">पदको नाम / तह / सेवा / समुह </td>
                                <td class="text-center"  style="width: 20%;">कार्यालय को नाम / रहेको स्थान </td>
                                <td class="text-center"  style="width: 10%;">नियुक्ति वा बढुवाको मिति </td>
                                <td class="text-center"  style="width: 10%;">बहाल रहेको मिति </td>
                                <td class="text-center"  style="width: 10%;">असाधारण बिदा बसेको अबिधि </td>
                                <td class="text-center"  style="width: 10%;">कसरी आएको </td>
                                <td class="text-center"  style="width: 10%;">कैफियत </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>शुरू नियुक्ति </td>
                                <td class="text-center"> <?php echo $JobStart['DESIGNATION_TITLE'] .' / '. $JobStart['FUNCTIONAL_LEVEL_EDESC'] .' / '. $JobStart['SERVICE_TYPE_NAME'] .' / '. $JobStart['DEPARTMENT_NAME'] ?></td>
                                <td class="text-center"> <?php echo $JobStart['BRANCH_NAME'] .' / '. $JobStart['LOCATION_EDESC']?></td>
                                <td class="text-center"> <?php echo $JobStart['START_DATE'] ?></td>
                                <td class="text-center"> <?php echo $JobStart['SERVICE_TYPE_NAME'] ?></td>
                                <td class="text-center"> <?php echo $casLeaveEarlier ?></td>
                                <td class="text-center"> <?php echo $JobStart['SERVICE_TYPE_NAME'] ?></td>
                                <td class="text-center"> <?php echo $JobStart['REMARKS'] ?></td>
                            </tr>
                            <tr>
                                <td>हालको पद / तह </td>
                                <td class="text-center"> <?php echo $JobEnd['DESIGNATION_TITLE'] .' / '. $JobEnd['FUNCTIONAL_LEVEL_EDESC'] .' / '. $JobEnd['SERVICE_TYPE_NAME'] .' / '. $JobEnd['DEPARTMENT_NAME'] ?></td>
                                <td class="text-center"> <?php echo $JobEnd['BRANCH_NAME'] ?></td>
                                <td class="text-center"> <?php echo $JobEnd['START_DATE'] ?></td>
                                <td class="text-center"> <?php echo $JobEnd['SERVICE_TYPE_NAME'] ?></td>
                                <td class="text-center"> <?php echo $casLeaveLater ?></td>
                                <td class="text-center"> <?php echo $JobEnd['SERVICE_TYPE_NAME'] ?></td>
                                <td class="text-center"> <?php echo $JobEnd['REMARKS'] ?></td>
                            </tr>
                        </tbody>
                    </table>
                    <h5 class="bold">द्रष्टब्य : </h5>
                    <p> १ . सेवा , समुह परिवर्तन के हो स्पष्ट उलेख गर्ने। <br>  
                        २. बढुवाको उमेद्वार हुन असर पर्ने कुनै कुरा छैन भनि कैफियत महलमा उलेख गरि दस्तखत समेत गर्ने। <br>
                        ३. गयल कट्टी लगायत सेवा अवधि गणना नहुने कुनै बिवरण भए कैफियत महलमा खुलाउनु पर्नेछ। <br>
                        ४. माथि कार्यालयमा रहेको स्थानमा हालको पदको बिवरण खुलाउदा  विनियम ६।११ (२) बमोजिम वर्ग उलेख गर्नु पर्ने। 
                    </p>
                </div>
                    <h5 class="bold">२. शैक्षित योग्यता ( विनियम ६। १२ ( १ ) अनुसारको मात्र )</h5>
                <div class="row">
                <h5> <strong> <?php echo $detail['REMARK']; ?> </strong></h5>
                    <div id="quaConId">
                        <div id="rootwizard" class="tabbable-custom">
                            <div class="status-info">
                                <p><i class="fa fa-info-circle ticon ticon"></i>Current qualification details</p>
                                <div class="row clearfix e-setup">
                                    <div class="col-sm-12">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-bordered table-hover no-footer customtbl profile-table-header" id="qualificationTbl">
                                                <tr>
                                                    <td><label>Faculty</label></td>
                                                    <td><label>Level</label></td>
                                                    <td><label>Degree Acquired</label></td>
                                                    <td><label>Rank Type</label></td>
                                                    <td><label>Rank Value</label></td>
                                                    <td><label>University / Board</label></td>
                                                    <td><label>Passed Year</label></td>
                                                </tr>
                                                <?php
                                                foreach ($EducationData as $eduData) {
                                                ?>
                                                    <tr>
                                                        <td>
                                                            <?php print $eduData['ACADEMIC_PROGRAM_ID']; ?>
                                                        </td>
                                                        <td>
                                                            <?php print $eduData['ACADEMIC_DEGREE_ID']; ?>
                                                        </td>
                                                        <td>
                                                            <?php print $eduData['ACADEMIC_COURSE_ID']; ?>
                                                        </td>                                                       
                                                        <td>
                                                            <?php print $eduData['RANK_TYPE']; ?>
                                                        </td>
                                                        <td>
                                                            <?php print $eduData['RANK_VALUE']; ?>
                                                        </td>
                                                        <td>
                                                            <?php print $eduData['ACADEMIC_UNIVERSITY_ID']; ?>
                                                        </td>
                                                        <td>
                                                            <?php print $eduData['PASSED_YEAR']; ?>
                                                        </td>

                                                    </tr>
                                                <?php } ?>

                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                       
                    </div>
                    <div class="row clearfix e-setup">
                    <!-- Select inclusion -->
                    <div>
                       
                    <div class="row clearfix e-setup">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box">
                            <h5><strong>समावेशीकरण छान्नुहोस्</strong> </h5>

                        </div>
                    </div>

                    <div class="row clearfix e-setup">
                        <div class="col-xs-12 col-sm-3 col-md-8 col-box">
                            <div class="row bottomgap">
                                <div class="form-group">
                                <div class="col-xs-6 col-sm-6 col-md-2 col-box">
                                </div>
                            
                                    <?php foreach($inclusions as $inclusion) {?>
                                    <div class="col-xs-6 col-sm-6 col-md-2 col-box">
                                    <?php if (in_array( $inclusion['INCLUSION_ID'], $inclusionIds)) {?>
                                    <input disabled class="form-check-input inclusion" type="checkbox" name="inclusion[]" checked value="<?php echo $inclusion['INCLUSION_ID']; ?>"> 
                                        <label class="form-check-label"><?php echo $inclusion['OPTION_EDESC']; ?></label>
                                    <?php } else { ?>
                                        <input disabled class="form-check-input inclusion" type="checkbox" name="inclusion[]" value="<?php echo $inclusion['INCLUSION_ID']; ?>"> 
                                        <label class="form-check-label"><?php echo $inclusion['OPTION_EDESC']; ?></label>
                                    <?php } ?>
                                    
                                    </div>
                                    <?php } ?>
                                </div>
                                <div class="col-xs-12 col-sm-3 col-md-2 col-box">
                                    <div class="row bottomgap">
                                        <div class="form-group">
                                            <div class="col-xs-6 col-sm-6 col-md-6 rightalign">
                                                <label for="amount">रकम :</label>
                                            </div>
                                            <div class="col-xs-6 col-sm-6 col-md-6 cgap">
                                                <input type="text" class="form-control form-control-sm" name="inclusion_amount" id="inclusion_amount" value="<?php echo $application_amount ?>" readonly>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h6> <strong> </strong></h6>
                    <div class="row clearfix e-setup">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box">
                            <h5><strong> कागजात र प्रमाणपत्र (JPG | PNG मात्र)</strong> </h5>
                        </div>
                    </div>
                    <hr>
                    <div class="container">
                        <div class="row" >
                            <div >							
                                <h4>Note: 1. This vacancy require up to <strong> <?php echo $detail['QUALIFICATION'];  ?> </strong> degree documents, please upload it all else your application will not get approved.</h4>
                                <h4>  2. Please upload all respective document in single a file.</h4>
                            </div>
                            <table class="table table-responsive-lg table-striped table-bordered table-sm">
                                <thead>
                                    <tr class="UploadDoc">
                                        <td>S.No</td>
                                        <td>Document Name</td>
                                        <td>Upload</td>
                                        <!-- <td>Add</td> -->
                                    </tr>
                                </thead>							
                                <tbody>
                                    <?php /* <tr>
                                        <?php $c = 1; foreach($certificates as $certificate) {?>
                                        <tr class="certificate">
                                            <td><?php echo $c; ?></td>
                                            <td>											
                                                <div class="form-group">
                                                    <p><?php echo ucfirst($certificate['ACADEMIC_DEGREE_NAME']);  ?></p>										
                                                </div>
                                            </td>
                                            <?php
                                            foreach ($existingDocuments as $key => $existingDocument) {
                                                if (array_key_exists($certificate['ACADEMIC_DEGREE_NAME'].' Certificate',$existingDocument)) {
                                                ?> <td class='certInput'>
                                                    <a class="btn-delete"
                                                        href="<?= $this->basePath() . "/uploads/documents/" . implode('_',explode(' ',$existingDocument['name'])) . "/" . $existingDocument['path']; ?>"
                                                        download="<?php echo  $existingDocument['name']; ?>" style="height:27px;">
                                                        <i class="fa fa-download"></i>
                                                    </a>
                                                    <?php /* <a class="btn-delete" href="#" onclick="uploadDocument()"> <i class="fa fa-edit"></i></a>
                                                    <div class="modal fade" id="documentUploadModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Update <?php echo ucfirst($certificate['ACADEMIC_DEGREE_NAME']);  ?> Certificate</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <input type="file" class="form-control" name="<?php echo ucfirst($certificate['ACADEMIC_DEGREE_NAME']);  ?>" id="file<?php echo $key ?>">
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" onclick="uploadCancelBtn(<?php echo $key ?>)" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                                <button type="button"  data-dismiss="modal" class="btn btn-primary">Update</button>
                                                            </div>
                                                            </div>
                                                        </div>
                                                        </div>?>
                                                </td>

                                                <?php break;
                                                }
                                            }
                                            ?>
                                        </tr>
                                        <?php $c++; } ?>
                                    </tr>	*/ ?>	
                                    <tr class="certificate">
                                        <td>1</td>
                                        <td>											
                                            <div class="form-group">
                                                <p>Qualification</p>										
                                            </div>
                                        </td>
                                        <td colspan="7">
                                            <a href="<?php echo $this->basePath($applicantsDocumentNew['qualification_trascript']); ?>" target="_blank" class="btn btn-primary">Transcript</a>
                                            <a href="<?php echo $this->basePath($applicantsDocumentNew['qualification_character']); ?>" target="_blank" class="btn btn-primary">Character</a>
                                            <?php if(!empty($applicantsDocumentNew['qualification_equivalent'])){ ?>
                                            <a href="<?php echo $this->basePath($applicantsDocumentNew['qualification_equivalent']); ?>" target="_blank" class="btn btn-primary">Equivalent</a>
                                            <?php } ?>
                                            <?php if(!empty($applicantsDocumentNew['qualification_council'])){ ?>
                                            <a href="<?php echo $this->basePath($applicantsDocumentNew['qualification_council']); ?>" target="_blank" class="btn btn-primary">Council</a>
                                            <?php } ?>
                                            <?php if(!empty($applicantsDocumentNew['qualification_license'])){ ?>
                                            <a href="<?php echo $this->basePath($applicantsDocumentNew['qualification_license']); ?>" target="_blank" class="btn btn-primary">Driving License</a>
                                            <?php } ?>
                                        </td>
                                    </tr>						
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <table class="table table-responsive-lg table-sm form-cstm-table">
                        <tr>
                            <td>
                                <div id="imagePreviewright_finger_scan" style="border: 1px solid; width: 160px; height: 140px;background-color:#f2f2f2;">
                                    <img  style="width: 100%; height: 100%" id="right_finger" src="<?php echo $this->basePath($applicantsDocumentNew['FingerPrintR']) ?>" />
                                    <label for="FingerPrintR">Finger Print Right</label>
                                </div>
                            </td>
                            <td>
                                <div id="imagePreviewleft_finger_scan" style="border: 1px solid; width: 160px; height: 140px;background-color:#f2f2f2;">
                                    <img style="width: 100%; height: 100%" id="left_finger" src="<?php echo $this->basePath($applicantsDocumentNew['FingerPrintL']) ?>" alt="Left Finger" />
                                    <label for="FingerPrintR">Finger Print Left</label>
                                </div>
                            </td>
                            
                            <td>
                                <div id="imagePreviewsignature" style="border: 1px solid; width: 160px; height: 140px;background-color:#f2f2f2;">
                                    <img style="width: 100%; height: 100%" id="recent_sign" src="<?php echo $this->basePath($applicantsDocumentNew['Signature'])?>" alt="Recent Signature" />
                                    <label for="FingerPrintR">Signature</label>
                                </div>
                            </td>

                            <td>
                                <div id="imagePreviewright_finger_scan" style="border: 1px solid; width: 160px; height: 140px;background-color:#f2f2f2;">
                                    <img  style="width: 100%; height: 100%" id="right_finger" src="<?php echo $this->basePath($applicantsDocumentNew['CitizenshipF']) ?>" />
                                    <label for="FingerPrintR">Citizenship Front</label>
                                </div>
                            </td>
                            <td>
                                <div id="imagePreviewleft_finger_scan" style="border: 1px solid; width: 160px; height: 140px;background-color:#f2f2f2;">
                                    <img style="width: 100%; height: 100%" id="left_finger" src="<?php echo $this->basePath($applicantsDocumentNew['CitizenshipB']) ?>" alt="Left Finger" />
                                    <label for="FingerPrintR">Citizenship Back</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td style="border-top:0;">
                                <div class="form-group">
                                    <input type="hidden" name="image_ids[]" value="right_finger_scan" />
                                    <p class="size"></p>
                                    <?php if (isset($upload_error_photo)) {
                                        echo $upload_error_photo;
                                    } ?>
                                </div>
                            </td>
                            <td style="border-top:0;">
                                <div class="form-group">
                                    <input type="hidden" name="image_ids[]" value="left_finger_scan" />
                                    <p class="size"></p>
                                </div>
                            </td>
                            <td style="border-top:0;">
                                <div class="form-group">
                                    <input type="hidden" name="image_ids[]" value="signature" />
                                    <p class="size"></p>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <h5 class="bold">द्रष्टब्य : </h5>
                    <p> १. माथि उल्लेखित सबै उपाधिहरुको प्रमाणित प्रतिलिपि पेश गर्नु पर्नेछ। <br>  
                        २. बढुवा हुने पदको लागि तोकिएको न्यूनतम शैक्षिक योग्यताको सम्बधमा तोकिएको शैक्षिक योग्यताको प्रमाणपत्र वा समकक्षता र सम्बंद्वाता निर्धारण भएकोमा सोको कागजात समेत पेश गर्नु पर्नेछ।  <br>
                       <br> <br>
                       माथि उल्लेखित बिवरण कुनै कुरा झुठा लेकिएको वा जानी जानी साचो कुरा दवाउने उद्हेश्ले लेखिएको ठहरे कानुन बमोजिम सजाय स्वीकार गर्ने छु भनि सहिछाप गर्ने। 
                    </p>
                </div>
            </div>
            <?php
            //print $this->formSubmit($submit);
            print $this->form()->closeTag();
            ?>
            <div class="border-bottom">
            </div>
        </div>
    </div>
</div>