
<?php

$this->headScript()->appendFile($this->basePath('js/document-registration/add.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'))
    ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basePath('dropzone/dropzone.min.js'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'registration-form');

$registrationTempCode = $form->get('registrationTempCode');
// $registrationTempCode->setAttribute('value',$regTempCode);
// $registrationTempCode->setAttribute('readonly','readonly');
$registrationDate = $form->get('registrationDate');
$completionDate = $form->get('completionDate');
$receivingLetterReferenceNo = $form->get('receivingLetterReferenceNo');
// $senderOrganization = $form->get('senderOrganization');
$description = $form->get('description');
$receivingLetterReferenceDate = $form->get('receivingLetterReferenceDate');
$receivingDepartment = $form->get('receivingDepartment');
$receiverName = $form->get('receiverName');
$documentDate = $form->get('documentDate');
// $filesUpload = $form->get('filesUpload');
$responseFlag = $form->get('responseFlag');
$choiceFlag = $form->get('choiceFlag');
$sbFiscalYear = $form->get('sbFiscalYear');
$sbEmployeeId = $form->get('employeeId');

$choiceFlagKS = $form->get('choiceFlagKS');
$ksFiscalYear = $form->get('ksFiscalYear');
$ksEmployeeId = $form->get('empId');

$remarks = $form->get('remarks');

$submit = $form->get('submit');

$form->setAttribute('action', $this->url('incoming-document', ['action' => 'add']));
$form->prepare();

?>
<script>
document.pushDCFileLink = '<?php echo $this->url('incoming-document', ['action' => 'pushDCFileLink']); ?>';
    document.uploadUrl = '<?= $this->url('incoming-document', ['action' => 'fileUpload']); ?>';
    document.date = '<?=date('d-M-Y')?>';
</script>

<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i>
                    Add New Incomming Documents
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <?php print $this->form()->openTag($form);?>
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group <?=empty($receivingLetterReferenceNo->getMessages()) ? "" : "has-error"?>">
                            <?php print $this->formLabel($receivingLetterReferenceNo);?>
                            <?php print $this->formElement($receivingLetterReferenceNo);?>
                            <?php print $this->formElementErrors()->render($receivingLetterReferenceNo, ['class' => 'help-block error']);?>
                        </div>
                    </div>
                    <div class="col-sm-4">

                    
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($receivingLetterReferenceDate);?>
                                    <?php print $this->formElement($receivingLetterReferenceDate);?>
                                    <?php print $this->formElementErrors()->render($receivingLetterReferenceDate, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliReceivingLetterReferenceDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliReceivingLetterReferenceDate" id="nepaliReceivingLetterReferenceDate" placeholder="Date in Nepali"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                       
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($documentDate);?>
                                    <?php print $this->formElement($documentDate);?>
                                    <?php print $this->formElementErrors()->render($documentDate, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliDocumentDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliDocumentDate" id="nepaliDocumentDate" placeholder="Date in Nepali"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class=" row">
                    <div class="col-sm-4">
                    <label>From Office</label>
                    <select class="form-control" name="fromOfficeId" id="fromOfficeId">
                            <?php  foreach($officeList as $key => $value) {  ?>
                            <option value='<?=$key?>'><?=$value?></option>
                            <?php } ?> 
                        </select>
                    </div>
                    <div class=" col-sm-4 ">
                        <div class="form-group">
                            <?php print $this->formLabel($description);?>
                            <?php print $this->formElement($description);?>
                            <?php print $this->formElementErrors()->render($description, ['class' => 'help-block error']);?>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                    <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($registrationDate);?>
                                    <?php print $this->formElement($registrationDate);?>
                                    <?php print $this->formElementErrors()->render($registrationDate, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliRegistrationDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliRegistrationDate" id="nepaliRegistrationDate" placeholder="Date in Nepali"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" row">
                    
                    <div class="col-sm-4">
                        <div class="form-group <?=empty($remarks->getMessages()) ? "" : "has-error"?>">
                            <?php print $this->formLabel($remarks);?>
                            <?php print $this->formElement($remarks);?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block error']);?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group" id="responseFlagged">
                            <?php print $this->formLabel($responseFlag);?>
                            <?php print $this->formElement($responseFlag);?>
                            <?php print $this->formElementErrors()->render($responseFlag, ['class' => 'help-block error']);?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="row" id="completionDt">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($completionDate);?>
                                    <!-- <span class="required" aria-required="true">*</span> -->
                                    <?php print $this->formElement($completionDate);?>
                                    <?php print $this->formElementErrors()->render($completionDate, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nepaliCompletionDate">&nbsp;</label>
                                    <div class="input-group">
                                        <input type="text" name="nepaliCompletionDate" id="nepaliCompletionDate" placeholder="Date in Nepali"
                                               class="form-control" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               
                <div class= "row">    
                    <div class="col-sm-4">
                        <div class="row" id="sampatiBibaran">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($choiceFlag);?>
                                    <?php print $this->formElement($choiceFlag);?>
                                    <?php print $this->formElementErrors()->render($choiceFlag, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div  id="sbFisYr">
                                <div class="col-sm-6">
                                    <label>Fiscal Year:</label>
                                    <select class="form-control" name="sbFiscalYear" id="sbFiscalYear">
                                        <?php  foreach($fiscalYear as $key => $value) {  ?>
                                        <option value='<?=$key?>'><?=$value?></option>
                                        <?php } ?> 
                                    </select>
                                </div>
                            </div>
                            <div  id="employeee">
                                <div class="col-sm-6">
                                    <label>Employee Name:</label>
                                    <select class="form-control" name="employeeId" id="employee">
                                        <?php  foreach($employee as $key => $value) {  ?>
                                        <option value='<?=$key?>'><?=$value?></option>
                                        <?php } ?> 
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <!-- ---------------------------------------------------------------------------------------------------------- -->
                <div class= "row">    
                    <div class="col-sm-4">
                        <div class="row" id="karyaSampadan">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <?php print $this->formLabel($choiceFlagKS);?>
                                    <?php print $this->formElement($choiceFlagKS);?>
                                    <?php print $this->formElementErrors()->render($choiceFlagKS, ['class' => 'help-block error']);?>
                                </div>
                            </div>
                            <div  id="ksFisYr">
                                <div class="col-sm-6">
                                    <label>Fiscal Year:</label>
                                    <select class="form-control" name="ksFiscalYear" id="ksFiscalYear">
                                        <?php  foreach($fiscalYear as $key => $value) {  ?>
                                        <option value='<?=$key?>'><?=$value?></option>
                                        <?php } ?> 
                                    </select>
                                </div>
                            </div>
                            <div  id="employeeee">
                                <div class="col-sm-6">
                                    <label>Employee Name:</label>
                                    <select class="form-control" name="empId" id="employee2">
                                        <?php  foreach($employee as $key => $value) {  ?>
                                        <option value='<?=$key?>'><?=$value?></option>
                                        <?php } ?> 
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <!-- ---------------------------------------------------------------------------------------------------------- -->
                <div class= "row">
                <div class=" col-md-6 form-group">
                        <table id="fileDetailsTbl" class="table">
                            <tr>
                                <th>Document</th>
                                <th>&nbsp;</th>
                                <th>Action</th>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-3">
                        <button id="addDocument" type="button" class="btn btn-primary">
                            Add
                        </button>
                    </div>
                </div>


                <?php
print $this->formSubmit($submit);
print $this->form()->closeTag();
?>
            </div>
        </div>
    </div>
</div>

<!--bootstrap modal-->
<div id="documentUploadModel" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Document Upload</h4>
            </div>
            <div class="modal-body">
                <div class="modal-body" id="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!--<div id="dropZoneContainer" >-->
                            <div id="dropZoneContainer"  class="dropzone">
                            </div>
                            <div id="uploadErr">Please upload .pdf or .txt or .jpg or .png files only.</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button id='uploadSubmitBtn' class="btn btn-primary" type="button" >OK</button>
            <button id='uploadCancelBtn' class="btn btn-warning" type="button" >Cancel</button>
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        </div>
    </div>
</div>