<?php
//Load JS files here
$this->headLink()
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
        ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.css'))
        ->appendStylesheet($this->basePath('sweet_alert/dist/sweetalert2.min.css'));
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));
    
$this->headScript()
        ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'))
        ->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'))
        ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/document-registration/incomingDocumentSearch.js'));
?> 

<script>
    document.viewLink = '<?= $this->url("incoming-document", ["action" => "view"]) ?>';
    document.editLink = '<?= $this->url("incoming-document", ["action" => "edit"]) ?>';
    document.deleteLink = '<?= $this->url("incoming-document", ["action" => "delete"]) ?>';
    document.forwardLink = '<?= $this->url("incoming-document", ["action" => "forward"]) ?>';
    document.acknowledgeLink = '<?= $this->url("incoming-document", ["action" => "acknowledge"]) ?>';
    document.getAllIncoming = '<?= $this->url("incoming-document", ["action" => "getAllIncomingData"]) ?>';
    document.getAllIncomingDatabyIdAction = '<?= $this->url("incoming-document", ["action" => "getAllIncomingDatabyId"]) ?>';
    //document.orgs = <?php //echo json_encode($orgs); ?>;
    // document.dept = <?php //echo json_encode($dept); ?>;
    //document.response = <?php //echo json_encode($response); ?>;
    document.endProcess = '<?php echo($endProcess); ?>';

</script>
<div id="incomingDocumentList" >
    <div class="portlet light bg-inverse">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-paper-plane font-green-haze"></i>
                <span class="caption-subject bold font-green-haze uppercase"> Filter Incoming Documents</span>
            </div>
            <div class="tools">
                <a  class="collapse"></a>
                <a  class="fullscreen"></a>
            </div>
            <div class="actions">
                <a href="<?= $this->url('incoming-document', ['action' => 'add']) ?>" class="btn default btn-sm">
                    <i class="fa fa-plus-square icon-black"></i> New </a>
                <div class="btn-group">
                    <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-copy"></i> Tools<i class="fa fa-angle-down "></i>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li >
                            <a href="javascript:;" id="excelExport">
                                <i class="fa fa-file-excel-o" ></i> Export to Excel </a>
                        </li>
                        <li >
                            <a href="javascript:;" id="pdfExport">
                                <i class="fa fa-file-pdf-o" ></i> Export to PDF </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
            <div class="row margin-top-1">
                <div class="col-sm-3">
                    <label>Registration Number</label>
                    <input type="text" class="form-control" name="registrationNum" id="registrationNum"/>
                </div>
                <div class="col-sm-3">
                    <label>From Office</label>
                    <select class="form-control" name="senderOrg" id="senderOrg">
                    <?php  foreach($organizationList as $key => $value) {  ?>
                        <option value='<?=$key?>'><?=$value?></option>
                    <?php } ?> 
                    </select>
                </div>
                <div class="col-sm-3">
                    <label>Receiving Department</label>
                    <select class="form-control" name="receivingDept" id="receivingDept">
                    <?php  foreach($dept as $key => $value) {  ?>
                        <option value='<?=$key?>'><?=$value?></option>
                    <?php } ?> 
                    </select>
                </div>
                <div class="col-sm-3">
                    <label>Letter Ref No.</label>
                    <input type="text" class="form-control" name="letterReferenceNum" id="letterReferenceNum"/>
                </div>
    
            </div>
            <div class="row margin-top-30">
            <label style="padding:15px;">Letter Ref. Date:</label>
            </div>
            <div class="row margin-top-20 ">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>From Date(AD)</label>
                        <input type="text" id="fromDate" name="fromDate"  class="form-control" placeholder="From Date"/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>From Date(BS)</label>
                        <input type="text" id="nepaliFromDate" name="nepaliFromDate" class="form-control" placeholder="From Date Nepali"/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>To Date(AD)</label>
                        <input type="text" id="toDate" name="toDate"  class="form-control" placeholder="To Date"/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>To Date(BS)</label>
                        <input type="text" id="nepaliToDate" name="nepaliToDate" class="form-control" placeholder="To Date Nepali"/>
                    </div>
                </div>

                <div class="col-sm-3">
                        <label>Location</label>
                        <select class="form-control" name="toLocationCode" id="toLocationCode">
                    <?php  foreach($locationList as $key => $value) {  ?>
                        <option value='<?=$key?>'><?=$value?></option>
                    <?php } ?> 
                    </select>
                    </div>       
            
            </div>
            </div>
            <div class="row margin-top-30">
                <div class="col-sm-4 col-sm-offset-8">
                    <button id="reset" class="btn default btn-sm pull-right hris-reset-btn ">
                        Reset
                        <i class="fa fa-refresh"></i>
                    </button>
                    <button id="search" class="btn btn-default btn-sm pull-right">
                        Search
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="incomingDocumentsTable">
    </div>
</div>